### ISSUE TITLE
.py extension

### ISSUE THREAD

**Issue by pixelrebel** [networktocode/ntc-ansible#100]
Is there a reason why two modules are missing their `.py` extension?

**Comment by jedelman8** [comment]
No, it was a timing thing.  The one's without it are a few months older and it was overlooked...no big deal :)  Will get it updated soon...

**Comment by pixelrebel** [comment]
Okay, cool. I'm new to ansible module development and thought there may be a reason.  Thanks!

**Comment by jedelman8** [comment]
Fixed a while back...
