### ISSUE TITLE
pip install ntc-ansible doesn't install terminal

### ISSUE THREAD

**Issue by networkop** [networktocode/ntc-ansible#110]
I was doing a new install on a freshly built ubuntu 14.04 server. 
1. Did a pip install ntc-ansible
2. Tried running playbook and got an error "This module requires TextFSM"
Apparently textfsm import failed but not due to textfsm but terminal missing.
So to workaround I had to do `pip install terminal`. After that everything worked.
Perhaps you could include it in your dependencies installation.

**Comment by slemire** [comment]
This should be fixed, I already submittted an issue to TextFSM and it has been closed:

https://github.com/google/textfsm/issues/6

**Comment by hosseinoliabak** [comment]
I am having almost the same issue when installing pyntc:
    pip3 install pyntc
    Could not find a version that satisfies the requirement textfsm==1.0.1 (from pyntc) (from versions: 0.3.2)
No matching distribution found for textfsm==1.0.1 (from pyntc)
But works on Python2. Any guide would be a great help. Regards,

**Comment by richwalker1988** [comment]
@hosseinoliabak, did you manage to resolve this? i have the same issue on windows with python 3.6
