### ISSUE TITLE
ansible playbook showing error while running 

### ISSUE THREAD

**Issue by amy201988** [networktocode/ntc-ansible#120]
I just installed ansible on a server in aws and then created a playbook to run the same but while running i am getting error as below :

ERROR! 'copy' is not a valid attribute for a Play

The error appears to have been in '/root/amritha/pega-cloud-infrastructure/ansible/roles/datadog-pegalogs-apptier/tasks/main.yml': line 3, column 3, but may be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

name: copy the pattern_search.txt file which has patterns to be grepped ^ here

And my playbook is as follows:

---

- name: copy the pattern_search.txt file which has patterns to be grepped
  copy: src=pattern_search.txt dest=/root/pattern_search.txt owner=root group=root mode=755

- name: copy the logsearchtest.sh script which greps patterns and prints pattern.txt file
  copy: src=logsearchtest.sh dest=/root/logsearchtest.sh owner=root group=root mode=755
  script: /root/logsearchtest.sh

- name: schedule cron to run every 5 minutes
  cron: name="logsearch script for grepping pega alert logs" minute="5" job="/root/logsearchtest.sh > /dev/null"

- name: copy parsers.py fucntion to datadog lib path
  copy: src=parsers.py dest=/opt/datadog-agent/agent/checks/libs/parsers.py owner=root group=root mode=755

- name: copy datadog agent configuration file
  copy: src=datadog-agent.conf dest=/etc/datadog.conf owner=root group=root mode=755

Also please note that i have a directory inside that i have files and tasks folder . and files folder have all mentioned files and tasks folder has the above playbook

**Comment by syn-ful** [comment]
It might be an indentation issue, but it's difficult to tell without proper formatting.  Can you re-post your playbook in a code-block using triple back-ticks \`\`\`  your playbook ```.  

Then it will format properly and make seeing indentation issues easier.
Example:
```YAML
 - name: copy the pattern_search.txt file which has patterns to be grepped
   copy: src=pattern_search.txt dest=/root/pattern_search.txt owner=root group=root mode=755
```

**Comment by jedelman8** [comment]
Please post how you are running it too.  You are using roles, so you still need a playbook that calls your role that executes the tasks in `main.yml`.

BTW, this repo is primarily for support of our ntc modules.  Are you using any of those? :)

**Comment by amy201988** [comment]
my playbook :

```---

- name: copy the pattern_search.txt file which has patterns to be grepped
  copy: src=pattern_search.txt dest=/root/ddmonitor/pattern_search.txt owner=root group=root mode=755

- name: copy the logsearchtest.sh script which greps patterns and prints pattern.txt file
  copy: src=logsearchtest.sh dest=/root/ddmonitor/logsearchtest.sh owner=root group=root mode=755
  script: /root/logsearchtest.sh

- name: schedule cron to run every 5 minutes
  #cron: */5 * * * * root /root/logsearchtest.sh -c "script to grep patterns;"
  cron: name="logsearch script for grepping pega alert logs" minute="5" job="/root/ddmonitor/logsearchtest.sh > /dev/null"

- name: copy parsers.py fucntion to datadog lib path
  copy: src=parsers.py dest=/opt/datadog-agent/agent/checks/libs/parsers.py owner=root group=root mode=755

- name: copy datadog agent configuration file
  copy: src=datadog-agent.conf dest=/etc/dd-agent/datadog.conf owner=root group=root mode=755```

**Comment by amy201988** [comment]
running using ansible-playbook -i "localhost," -c local main.yml

and i have a folder which has both files and tasks . The tasks folder has this main.yml and trying to run it in local host

**Comment by jedelman8** [comment]
I would suggest creating playbook.  You don't have a play definition at all
as main.yml is NOT a playbook, it's a task list.

Your playbook should start like this:

---
  - name: playbook...
    hosts: HOSTS_FROM_INVENTORY_FILE

   tasks:
        YOUR TASKS HERE

**Comment by amy201988** [comment]
yes my point is i need to just test this task as my playbook is as follows:

---
# file: pega-web.yml

- include: local-storage.yml
- include: common.yml

- hosts: all
  roles:
    - postgresql-access
    - pega-tomcat
    - pega-screenshot
    - logrotate
    - jmx-helper
    - datadog-monitoring-tomcat
    - logstash-forwarder
    - pgstudio
    - post-install
    - datadog-pegalogs-apptier

**Comment by amy201988** [comment]
yes my point is i need to just test this task as my playbook is as follows:

```---
# file: pega-web.yml

- include: local-storage.yml
- include: common.yml

- hosts: all
  roles:
    - postgresql-access
    - pega-tomcat
    - pega-screenshot
    - logrotate
    - jmx-helper
    - datadog-monitoring-tomcat
    - logstash-forwarder
    - pgstudio
    - post-install
	- datadog-pegalogs-apptier'```

**Comment by jedelman8** [comment]
Then I would suggest creating a smaller playbook and only having your ONE
role in it you want to test.

**Comment by amy201988** [comment]
How can I test this playbook 

And anyway to test only tasks ?
