### ISSUE TITLE
problems installing dependency lxml

### ISSUE THREAD

**Issue by bordeltabernacle** [networktocode/ntc-ansible#126]
When installing ntc-ansible using `sudo pip install ntc-ansible` the installation of `lxml` was failing, causing the installation of `ntc-ansible` to fail.

To fix this I had to install the following packages:

```
$ sudo apt-get -y install zlib1g-dev libxml2-dev libxslt-dev python-dev
```

This was in a new Ubuntu Trusty64 Vagrant machine.

**Comment by jedelman8** [comment]
Will add to the README.  Thanks.
