### ISSUE TITLE
ntc_save_config for IOS doesn't work without "file prompt quiet"

### ISSUE THREAD

**Issue by BobbyGR** [networktocode/ntc-ansible#133]
Running a playbook to download all of my configs for 2960's. 

...
  tasks:
- ntc_save_config:
    platform: "cisco_ios_ssh"
    local_file: "backups/{{ inventory_hostname }}.cfg"
    host:     "{{ ip }}"
    un/
    pw/
  '''

When executed it's able to get to the device but all devices get back

'IOError: Search pattern never detected in send_command_expect: ATL1-OS3P-2960-11034-R1C5#'

Reviewing, I can see that it's not expecting a prompt to occur, and with IOS a prompt occurs.
I tried to tackle this but not sure if editing your code or netmiko was the way to go. 
Or I can just run this command on everything 
"(config)#file prompt quiet" 
and call it a day. 

regardless out of the box it doesn't work.

**Comment by BobbyGR** [comment]
Note: works after performing this one little trick your doctor doesn't want you to know...

"changed: [XXX] => {"changed": true, "invocation": {"module_args": {"host": "X.X.X.X", "local_file": "X.com.cfg", "ntc_conf_file": null, "ntc_host": null, "password": "XXX", "platform": "cisco_ios_ssh", "port": null, "remull, "transport": null, "username": "YYY"}, "module_name": "ntc_save_config"}, "local_file": "backups/XXX Config)", "remote_save_successful": true}
"

**Comment by GGabriele** [comment]
This is an error raised by Netmiko. Are you using the latest release? I've just tested it and it worked for me.

**Comment by BobbyGR** [comment]
Successfully installed netmiko-1.1.0 pycparser-2.16 setuptools-28.6.1

Can you confirm on your 2960 you are running 15.X code?
I just updated Netmiko and still getting the error

sh run | inc file
file prompt quiet

you might already have disabled your file prompt?

**Comment by GGabriele** [comment]
I've tested it on on a virtual 16.X without disabling the file prompt (I've verified it).

**Comment by BobbyGR** [comment]
can you confirm 16.x?  If it's me then i'd like to know but we are on the latest 15.2 that just came out.  It's across the board on over 300+ 2960's where if that command is not there it fails.  Ill bring it up in Netmiko as even if you can re produce it comes down to that repo.

**Comment by GGabriele** [comment]
```
csr1#sh run | inc file
csr1#show vers
Cisco IOS XE Software, Version 16.03.01
Cisco IOS Software [Denali], CSR1000V Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 16.3.1, RELEASE SOFTWARE (fc3)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2016 by Cisco Systems, Inc.
Compiled Tue 02-Aug-16 18:36 by mcpre
```

That's an IOS-XE image, which is handled just like an IOS by Netmiko... unfortunately I don't have a 2960 for testing. One thing you can try is to test native Netmiko on Python like this:

```
from netmiko import ConnectHandler
your_device = {
    'device_type': 'cisco_ios',
    'ip':   'ip',
    'username': 'un',
    'password': 'pwd'
}
net_connect = ConnectHandler(**your_device )
```

**Comment by BobbyGR** [comment]
Ah yeah, you are running the linux/ASR flavor of IOS.  

Cisco IOS Software, C2960S Software (C2960S-UNIVERSALK9-M), Version 15.2(2)E5, RELEASE SOFTWARE (fc2)

Is what i'm running.

**Comment by GGabriele** [comment]
Hey @BobbyGR , have you tested native Netmiko? Is it working?

**Comment by jasonbarbee** [comment]
I just ran into the same issue with the search pattern in the opening thread. Without pushing the file prompt quiet everywhere, this works well for me. It will probably fail with the quiet command on though... 

I modified the pyntc library file "devices/ios_device.py" as below:
https://github.com/networktocode/pyntc

def save(self, filename='startup-config'):
            command = 'copy running-config %s' % filename
            expect_string = '\[%s\]' % filename
            self.show(command, expect=True, expect_string=expect_string)
            expect_string = '\[OK\]'
            self._send_command('\n', expect=True, expect_string=expect_string)
            return True

**Comment by GGabriele** [comment]
Hi @jasonbarbee ,
have you met this issue while testing it with the latest code?

**Comment by jasonbarbee** [comment]
@GGabriele yes, I was testing this on latest code from CVS copied to my python lib folder, which included your most recent commit in Sept to that save section. I was testing on older Cisco 2950 switches, after this 2 line change, it worked.

**Comment by jasonbarbee** [comment]
@GGabriele Apologies if I have mangled the PR today, I can delete and resubmit, I'm still figuring out pull requests, but I submitted a modified change. I tried my original change on newer gear and it failed. I removed the requirement for the [OK] and used some methods that do not require the prompt or expect that OK, in case the user has enabled file prompt quiet, or if they are using the default mode it also works fine with noisy mode.

**Comment by GGabriele** [comment]
@jasonbarbee We've merged your PR weeks ago, but I forgot to post here...do you think we can close this?

https://github.com/networktocode/pyntc/pull/10

**Comment by jasonbarbee** [comment]
yeah, it's at least been stable for me. I had to extend this delay factor one other time with a 2950 I think.  If I run into it again I'll try to submit something.
Thanks!

**Comment by GGabriele** [comment]
Thank you @BobbyGR !
