### ISSUE TITLE
ntc_show_command failing with"module (setup) is missing interpreter line"

### ISSUE THREAD

**Issue by cmacnevin** [networktocode/ntc-ansible#138]
Not sure if this is an issue with ntc or the core module. I've reinstalled a number of ways, with no luck. It's a simple test which isn't working:

tasks:
        ntc_show_command:
        ntc_hosts: test
                  connection=ssh
                  platform=cisco_ios_ssh
                  command=show ver 
                  username=admin
                  password=XXXXXX

TASK [Gathering Facts] ******************************************************************************
fatal: [switch02.backvport.sv2.tellme.com]: FAILED! => {"failed": true, "msg": "module (setup) is missing interpreter line"}

Version info:

ca-cmacnevi-mac:ansible christian.macnevin$ ansible --version
ansible 2.3.0 (devel 65f019fe82) last updated 2016/11/09 09:58:07 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 2584fca0ae) last updated 2016/11/09 09:58:29 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD a1dcbf9ce5) last updated 2016/11/09 09:58:30 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/christian.macnevin/ansible/library/']

**Comment by jedelman8** [comment]
Do you have any other module working with Ansible?  
Just curious if you're using python virtual environments too?

**Comment by jedelman8** [comment]
Actually, can you post your full playbook?

Want to make sure you have `connection: local` in your play definition like this.

```
---
  - name: DEBUGGING VARIABLES
    hosts: all
    connection: local
    gather_facts: no
   
    tasks:
```

**Comment by jedelman8** [comment]
Also, use `host` and not `ntc_host` 


```
      - name: GET STRUCTURED DATA VIA CLI/SSH FOR CISCO NX
        ntc_show_command:
          connection=ssh
          platform=cisco_ios_ssh
          command='show vlan'
          host={{ inventory_hostname }}
          username={{ un }}  # or hard-code the creds like you have
          password={{ pwd }}
```

**Comment by cmacnevin** [comment]
I had connection: local in the inventory file. Added here though. Not using anything else
afaik.

It was just a first time test, so with your changes, the whole thing is:

`---

tasks:
        - name: testing ntc
          hosts: test
          connection: local
          gather_facts: no

        ntc_show_command:  
                  connection=ssh
                  host=test
                  platform=cisco_ios_ssh
                  command=show ver | inc image file
                  username=admin
                  password=3ISvFuWGs1s1
                  register=sw_ver
...               
`

And I'm still getting:

`PLAY [test] *****************************************************************************************

TASK [Gathering Facts] ******************************************************************************
fatal: [switch02.backvport.sv2.tellme.com]: FAILED! => {"failed": true, "msg": "module (setup) is missing interpreter line"}
	to retry, use: --limit @/Users/christian.macnevin/ansible/tet2.retry

PLAY RECAP ******************************************************************************************
switch02.backvport.sv2.tellme.com : ok=0    changed=0    unreachable=0    failed=1   `

**Comment by cmacnevin** [comment]
I think this is likely an ansible install issue. I'm trying to debug. If
you've run into anything helpful before with this, let me know. I recall
there
was something about pip over brew or the other way around. I've uninstalled
and reinstalled a few times to no avail, sadly.

**Comment by jedelman8** [comment]
I don't think it's an install issue.

Few things though:

* You should not have `connection: local` in your inventory.
* You cannot use pipe commands with ntc_show_command
* `register` needs to be on the same indent level as ntc_show_command
* Remember ntc_show_command is all about getting structured data back. If you just want raw text, you can use ios_command (in Core)


Simplify it.

```
      - name: GET STRUCTURED DATA VIA CLI/SSH
        ntc_show_command:
          connection=ssh
          platform=cisco_ios_ssh
          command='show vlan'
          host={{ inventory_hostname }}
          username={{ un }}
          password={{ pwd }}
        register: myvlans
```

**Comment by cmacnevin** [comment]
The whole thing now looks like this, and i'm still getting the same issue:

---

- name: get version from all devices, redudant typing, why do i need this?

  hosts: test

  connection: local

  gather_facts: True


  tasks:

          - name: get version

            ntc_show_command:

                    connection=ssh

                    platform=cisco_ios_ssh

                    command='show ver'

                    host={{ inventory_hostname }}

                    username=admin

                    password=XXXXXX

            register: sw_ver


...

~


ansible-playbook ver-test.yml


PLAY [get version from all devices, redudant typing, why do i need this?]
************************************************************************************************************************


TASK [Gathering Facts]
***************************************************************************************************************************************************************************

fatal: [switch02.backvport.sv2.tellme.com]: FAILED! => {"failed": true,
"msg": "module (setup) is missing interpreter line"}

to retry, use: --limit @/Users/christian.macnevin/ansible/ver-test.retry


PLAY RECAP
***************************************************************************************************************************************************************************************

switch02.backvport.sv2.tellme.com : ok=0    changed=0    unreachable=0
   failed=1

**Comment by cmacnevin** [comment]
I should point out, here's why I thought it was installation. It doesn't
matter if I'm using your module:

ca-cmacnevi-mac:ansible christian.macnevin$ ansible -m setup test

switch02.backvport.sv2.tellme.com | FAILED! => {

    "failed": true,

    "msg": "module (setup) is missing interpreter line"

}

**Comment by jedelman8** [comment]
Hard to tell what's going on, but I saw you had 2.3 installed....if that wasn't for a specific reason, I would wipe the current install and simply install with pip- you would then need to clone the modules from this repo.  Better to start with a clean install than using the latest dev branch which you have now.

**Comment by cmacnevin** [comment]
OK, I stripped out my whole ansible and some other stuff and started over.
I now have 2.1, and my setup test works. Now, having said
that, I'm getting a bunch of errors doing pip install ntc-ansible. Is that
your recommended method? Or better to clone the repo?

Thanks for your help so far

**Comment by cmacnevin** [comment]
OK, it turned out there's an issue with Six trying to uninstall the most
recent version on recent versions of OSX. I'm on Sierra. Fixed that, and
for now, it looks like things are starting to work. Thanks a bunch.

**Comment by GGabriele** [comment]
@cmacnevin Glad to hear this :) so you think we can close it?

**Comment by cmacnevin** [comment]
Go for it. Cheers
