### ISSUE TITLE
https://github.com/networktocode/ntc-ansible/issues/new

### ISSUE THREAD

**Issue by AnsibleAlex** [networktocode/ntc-ansible#139]
Hi
Thank you for giving ntc-ansible. Will appreciate a little help here.

I have the latest Ansible 2.2 installed in a virtualenv with cent OS. With virtualenv ntc-ansible is not working properly. It gives  an error "This module requires TextFSM") even when the gtextfsm modules are present. 
The setup does work in a non virtualenv.
How can I make ntc-ansible work within a virtualenv. ?? 
What am I missing that the textfsm module is not detected properly.

(venv) [ansible@localhost project]$ ansible --version
ansible 2.2.0.0
  config file = /home/ansible/project/ansible.cfg
  configured module search path = ['/home/ansible/project']
(venv) [ansible@localhost project]$ uname -a
Linux localhost.localdomain 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
(venv) [ansible@localhost project]$ 

#########################################################################
Ansible/Python path
#########################################################################
(venv) [ansible@localhost project]$ which ansible
~/venv/bin/ansible
(venv) [ansible@localhost project]$ which python
~/venv/bin/python

Ansible Hosts file:
--------------------
(venv) [ansible@localhost project]$ more hosts 
[cisco:vars]
username=cisco
password=cisco

[cisco]
192.168.56.51

#########################
Ansible Playbook:(venv) [ansible@localhost project]$ more site.yml
#########################

 -  name: GET STRUCTURED DATA BACK FROM CLI DEVICES

  hosts: all
  connection: local
  gather_facts: False

  tasks:
        - ntc_show_command:
            connection=ssh
            platform=cisco_ios_ssh
            command='show version'
            host={{ inventory_hostname }}
            username={{ username }}
            password={{ password }}

######################################
Error Running Playbook
#####################################

(venv) [ansible@localhost project]$ pwd
/home/ansible/project

(venv) [ansible@localhost project]$ more site.yml
venv) [ansible@localhost project]$ ansible-playbook site.yml 

PLAY [GET STRUCTURED DATA BACK FROM CLI DEVICES] *******************************

TASK [ntc_show_command] ********************************************************
fatal: [192.168.56.51]: FAILED! => {"changed": false, "failed": true, "msg": "This module requires TextFSM"}
        to retry, use: --limit @/home/ansible/project/site.retry

PLAY RECAP *********************************************************************
192.168.56.51              : ok=0    changed=0    unreachable=0    failed=1   
 

#########################################################################
PIP List
#########################################################################

(venv) [ansible@localhost project]$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
ansible (2.2.0.0)
cffi (1.9.1)
coverage (4.2)
cryptography (1.5.3)
enum34 (1.1.6)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
future (0.16.0)
gtextfsm (0.2.1)
idna (2.1)
ipaddress (1.0.17)
Jinja2 (2.8)
jsonschema (2.5.1)
junos-eznc (2.0.1)
lxml (3.6.4)
MarkupSafe (0.23)
mock (2.0.0)
ncclient (0.5.2)
netaddr (0.7.18)
netmiko (1.1.0)
ntc-ansible (0.1.0)
paramiko (2.0.2)
pbr (1.10.0)
pip (9.0.1)
pyasn1 (0.1.9)
pycparser (2.17)
pycrypto (2.6.1)
pyeapi (0.7.0)
pyntc (0.0.5)
pynxos (0.0.3)
pyserial (3.2.1)
PyYAML (3.12)
requests (2.11.1)
scp (0.10.2)
setuptools (28.8.0)
six (1.10.0)
terminal (0.4.0)
wheel (0.30.0a0)
(venv) [ansible@localhost project]$ 

/home/ansible/venv/lib/python2.7/site-packages
(venv) [ansible@localhost site-packages]$ ls -l
total 1600
--snip--
-rw-rw-r--.  1 ansible ansible  52010 Nov 12 14:09 gtextfsm-0.2.1-py2.7.egg
-rw-rw-r--.  1 ansible ansible    533 Nov 14 21:36 gtextfsm-0.2.1-py2.7.egg-info
--snip--
drwxrwxr-x.  2 ansible ansible   4096 Nov 14 21:36 textfsm
--snip--

**Comment by slemire** [comment]
Ansible works fine for me in virtualenv, I just grabbed TextFSM from the github repo and installed it with 'python setup.py install' instead of using pypi's gtextfsm. Although both textfsm and gtextfsm are the same code, the module name is different so ntc-ansible will fail the requirements check. You could change ntc-ansible's code to work around that but it's probably just easier to grab the textfsm repo and run setup.py on it inside your virtualenv.

**Comment by jedelman8** [comment]
# # @

**Comment by AnsibleAlex** [comment]
@slemire , May I know whether you are using RH/CentOS or ubuntu?.
I am using CentOS.
Downloaded the textfsm from https://github.com/google/textfsm.  Still doesn't work.
Also, if it makes a difference, this ( ansible, ntc-ansible)  is installed as a non-root user.

(venv) [ansible@localhost project]$ pip list

--snip--
textfsm (0.2.2)


venv) [ansible@localhost project]$ ansible-playbook  site.yml 

PLAY [GET STRUCTURED DATA BACK FROM CLI DEVICES] *******************************

TASK [ntc_show_command] ********************************************************
fatal: [192.168.56.51]: FAILED! => {"changed": false, "failed": true, "msg": "This module requires TextFSM"}
        to retry, use: --limit @/home/ansible/project/site.retry

PLAY RECAP *********************************************************************
192.168.56.51              : ok=0    changed=0    unreachable=0    failed=1

**Comment by slemire** [comment]
I'm running ubuntu 14.04 and 16.04, both work without any problem.

**Comment by GGabriele** [comment]
Hi @AnsibleAlex , can you test it again specifying the Python interpreter for Ansible on your inventory file like this?

`ansible_python_interpreter='python'`

**Comment by AnsibleAlex** [comment]
@GGabriele , That was it.!! Had been constantly checking this on cell   from bed..   :) 
 This is a very good morning.!!  broke  my head for the past two days.
Here it is now after defining the interpreter. 

Thanks for this tip. Trying to read up more on this at  https://github.com/ansible/ansible/issues/6345


(venv) [ansible@localhost project]$ more hosts 
[cisco]
192.168.56.51
[cisco:vars]
username=cisco
password=cisco
ansible_python_interpreter='python'


(venv) [ansible@localhost project]$ ansible-playbook site.yml 

PLAY [GET STRUCTURED DATA BACK FROM CLI DEVICES] *******************************

TASK [ntc_show_command] ********************************************************
ok: [192.168.56.51]

TASK [debug] *******************************************************************
ok: [192.168.56.51] => {
    "version": {
        "changed": false, 
        "response": [
            {
                "config_register": "0x2102", 
                "hardware": "7206", 
                "hostname": "Rtr", 
                "running_image": "", 
                "serial": "", 
                "uptime": "5 minutes", 
                "version": "12.4(7h)"
            }
        ], 
        "response_list": []
    }
}

PLAY RECAP *********************************************************************
192.168.56.51              : ok=2    changed=0    unreachable=0    failed=0   

(venv) [ansible@localhost project]$

**Comment by GGabriele** [comment]
@AnsibleAlex Awesome! I'm glad everything looks good now :)
