### ISSUE TITLE
ntc_save_config.py Error : AttributeError: 'CiscoIosSSH' object has no attribute 'send_command_timing'

### ISSUE THREAD

**Issue by AnsibleAlex** [networktocode/ntc-ansible#140]
Hi, I am running into the above error with ansible in the virtualenv  on CENT OS again.
Previous, I posted an issue with similar setting for ntc_show_command.py which got resolved by setting the python interpreter env variable in host file.

Playbook:

> ---
>   - name: PLAY - BACKUP
>     hosts: all
>     gather_facts: no
>     connection: local
>     tasks:
>       - name: SAVE AND BACKUP CONFIGS
>         ntc_save_config:
>           local_file={{ inventory_hostname }}.cfg
>           platform=cisco_ios_ssh
>           host={{ inventory_hostname }}
>           username={{ username }}
>           password={{ password }}
> 

Here is the issue when i run this playbook:

> 
>  An exception occurred during task execution. The full traceback is:
> Traceback (most recent call last):
>   File "/tmp/ansible_t3FItw/ansible_module_ntc_save_config.py", line 230, in <module>
>     main()
>   File "/tmp/ansible_t3FItw/ansible_module_ntc_save_config.py", line 217, in main
>     remote_save_successful = device.save()
>   File "/data/ansible/lib/python2.7/site-packages/pyntc-0.0.5-py2.7.egg/pyntc/devices/ios_device.py", line 127, in save
>     self.show('\n')
>   File "/data/ansible/lib/python2.7/site-packages/pyntc-0.0.5-py2.7.egg/pyntc/devices/ios_device.py", line 105, in show
>     return self._send_command(command, expect=expect, expect_string=expect_string)
>   File "/data/ansible/lib/python2.7/site-packages/pyntc-0.0.5-py2.7.egg/pyntc/devices/ios_device.py", line 79, in _send_command
>     response = self.native.send_command_timing(command)
> AttributeError: 'CiscoIosSSH' object has no attribute 'send_command_timing'
> fatal: [HOST]: FAILED! => {
>     "changed": false, 
>     "failed": true, 
>     "invocation": {
>         "module_name": "ntc_save_config" 
> 

Is this with pyntc module or netmiko CiscoIosSSH  not able to find the attribute specified in the error.
Can you please help or guide how I can fix this.

Also ,would like to know whether ntc-ansible has been tested on CentOS, within virtualenv?.
Most testing seems to be with Ubuntu
Thanks.

**Comment by GGabriele** [comment]
Hi @AnsibleAlex ,
The error (`AttributeError: 'CiscoIosSSH' object has no attribute 'send_command_timing'`) indicates that you're running an old version of Netmiko...can you try to upgrade and re-test it?

**Comment by AnsibleAlex** [comment]
Upgrading Netmiko resolved the error. Thank you again. Please close this issue.

**Comment by GGabriele** [comment]
Glad to hear this :)
