### ISSUE TITLE
relative path for template_dir does not seem to work

### ISSUE THREAD

**Issue by spikedrba** [networktocode/ntc-ansible#141]
Hi,

first off many thanks for this great module, it's super useful.

I've just followed the installation instructions, the module is installed in $ansible_root/library/ntc and it's correctly found by ansible. However when I test with a sample playbook I get the following error:

> fatal: [sw-221]: FAILED! => {"changed": false, "failed": true, "msg": "could not find or read index file"}

looking at the code, that error seems to come from here:

https://github.com/networktocode/ntc-ansible/blob/master/library/ntc_show_command.py#L371 . 

I added a module.log() right above to check what the dir evaluated to and I got back the default value, which exists, ie (ntc-templates/templates/index).

I noticed you can specify a path using template_dir so I tried that, using an absolute path, and it worked! This seems to suggest that somehow it's a problem with the relative path, but I'm not sure why, if it's coded this way it must be working for you/others, no clue what's up with my setup that breaks it.

In any case, I tried to log os.getcwd, and if isfile() tries to use a relative path to that, that will indeed not work as in my case that's the plays directory ($ansible_root/plays).

In case it helps here's my dir structure:
```
tree -L 2 -d
.
├── group_vars
├── host_vars
├── library
│   └── ntc <--- ntc-templates/templates/index exists
├── logs
├── plays
├── roles
...
│   ├── hp-procurve <--- module is used here
...
├── tmp
└── utils
```

thanks

**Comment by GGabriele** [comment]
Hi @spikedrba ,
are you testing using the path relative to where you're running the playbook? If you're running it on `hp-procurve`, you should use something like `template_dir=../library/ntc/ntc-templates/templates`

**Comment by spikedrba** [comment]
Hi @GGabriele,

if I don't specify the template_dir it takes the default of ntc-templates/templates . I suppose if I specified the path manually and used a relative one that'd work, but if I have to specify it I might as well go with a static one. My point is that if you follow the tutorial and don't specify one then things may not work with the default of ntc-templates/templates . So the problem isn't about relative paths Vs absolute paths per se, it's about default rel paths and the default ansible dir layout. makes sense?

**Comment by GGabriele** [comment]
Makes sense :)

I've specified `template_dir` on all examples with #151.

Thanks! @spikedrba
