### ISSUE TITLE
Issue using ntc_show_command

### ISSUE THREAD

**Issue by nncse** [networktocode/ntc-ansible#143]
Hi, am new here. I was wondering if somebody could help me out. I am seeing the problem "msg": "could not find or read index file". Although I have tried to directly point the index file in the yaml file but to no avail. Below is my entire error message and yaml file.

Thanks in advance.

TASK [GET LLDP NEIGHBORS] ******************************************************
task path: /home/user/ansible-files/ntc-ansible/ntc-templates/templates/auto-config-port-descriptions.yaml:16
Using module file /home/user/ansible-files/ntc-ansible/library/ntc_show_command.py
ESTABLISH LOCAL CONNECTION FOR USER: root
EXEC /bin/sh -c '( umask 77 && mkdir -p "echo $HOME/.ansible/tmp/ansible-tmp-1480704963.75-150827960692550" && echo ansible-tmp-1480704963.75-150827960692550="echo $HOME/.ansible/tmp/ansible-tmp-1480704963.75-150827960692550" ) && sleep 0'
PUT /tmp/tmpqGzeVA TO /home/user/.ansible/tmp/ansible-tmp-1480704963.75-150827960692550/ntc_show_command.py
EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1480704963.75-150827960692550/ /home/user/.ansible/tmp/ansible-tmp-1480704963.75-150827960692550/ntc_show_command.py && sleep 0'
EXEC /bin/sh -c '/usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1480704963.75-150827960692550/ntc_show_command.py; rm -rf "/home/user/.ansible/tmp/ansible-tmp-1480704963.75-150827960692550/" > /dev/null 2>&1 && sleep 0'
fatal: [c3548]: FAILED! => {
"changed": false,
"failed": true,
"invocation": {
"module_args": {
"command": "show lldp neighbors",
"connection": "ssh",
"delay": "1",
"file": null,
"host": "c3548",
"index_file": "/home/user/ansible-files/ntc-ansible/ntc_templates/templates",
"key_file": null,
"local_file": null,
"optional_args": {},
"password": "xxxxxxxx",
"platform": "cisco_nxos",
"port": "22",
"secret": null,
"template_dir": "/home/user/ansible-files/ntc-ansible/ntc_templates/templates",
"trigger_device_list": null,
"use_keys": false,
"use_templates": true,
"username": "admin"
},
"module_name": "ntc_show_command"
},
"msg": "could not find or read index file"
}
to retry, use: --limit @/home/user/ansible-files/ntc-ansible/ntc-templates/templates/auto-config-port-descriptions.retry

PLAY RECAP *********************************************************************
c3548 : ok=1 changed=0 unreachable=0 failed=1
YAML FILE:

 - name: GET LLDP NEIGHBORS
    ntc_show_command:
      connection: ssh
      platform: cisco_nxos
      index_file: /home/user/ansible-files/ntc-ansible/ntc_templates/templates
      template_dir: /home/user/ansible-files/ntc-ansible/ntc_templates/templates
      command: 'show lldp neighbors'
      host: "{{ inventory_hostname }}"
      username: 'admin'
      password: 'xxxxxxx'
      use_templates: True
    register: neighbors
    tags: neighbors

**Comment by AnsibleAlex** [comment]
Had the same issue. It got resolved after specifying the template_dir to the right folder.
In your case you seem to have the template_dir specified. Maybe you should check whether the "index" file is in the ntp template directory

**Comment by nncse** [comment]
Thanks AnsibleAlex! The index file is in my ntc-templates/templates folder but I am still receiving that error message. Any other thoughts?

user@e7ch1glmf01:~/ansible-files/ntc-ansible/ntc-templates/templates$ ls index
index

**Comment by GGabriele** [comment]
Hi @nncse ,
here you're setting this: `index_file: /home/user/ansible-files/ntc-ansible/ntc_templates/templates` . That's wrong, since `index_file` is used to pass in the index file name, which is `index` by default. Can you try removing this parameter?

**Comment by GGabriele** [comment]
I'm glad that worked for you :)
