### ISSUE TITLE
ansible playbook showing error while running

### ISSUE THREAD

**Issue by jhimes90** [networktocode/ntc-ansible#153]
I am trying to create a simple file copy playbook however I am having some issues, 

Here is the error: 

ERROR! 'host' is not a valid attribute for a Play

The error appears to have been in '/var/lib/awx/projects/test/site.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
-
  host: "xxx.xxx.xxx.xxx" (real IP is within the file)
  ^ here

Here is the playbook:

---
-
  host: "xxx.xxx.xxx.xxx"
  name: playbook
-
  become: true
  hosts: Test
  name: "apply config files 
  remote_user: ec2-user
-
  copy: "new settings.xml src:/tmp/setting.xml dest:/usr/share/apache-maven/conf/setting.xml owner:ec2-user group:ec2-user mode:0644 backup:yes"

**Comment by GGabriele** [comment]
Hi @jhimes90 ,

can you please re-copy and re-paste your playbook here between triple back quote "`"? This would help to catch any error on the playbook structure, as I think it may be your case.

**Comment by jhimes90** [comment]
( `---
-
  host: "xxx.xxx.xxx.xxx"
  name: playbook
-
  become: true
  hosts: Jenkins_Test_Slave
  name: "apply config files for Jenkins settings.xml"
  remote_user: ec2-user )

**Comment by GGabriele** [comment]
I don't know what you're trying to do here, but a sample playbook structure looks like this:

```
---

- name: PLAYBOOK NAME
  hosts: nxos # THIS IS THE NAME OF THE HOST/GROUP AS IT APPEARS FROM THE INVENTORY FILE
  connection: local
  gather_facts: no


  tasks:
  - name: GET TABLE
    debug: var={{ inventory_hostname }} # DEBUG IS THE NAME OF THE ANSIBLE MODULE USED
```

**Comment by jhimes90** [comment]
I am trying to copy a file from temp (for now) later it will be from GitHub to a location on a network server.

**Comment by GGabriele** [comment]
@jhimes90 Have you solved your issue stated here?
