### ISSUE TITLE
Run Module inside another script

### ISSUE THREAD

**Issue by compyy** [networktocode/ntc-ansible#158]
Hello,

I want to run this module inside another script.

In my script user provides, username/password/hostname and command line, my script determines which platform is it and then runs those show commands on that router.

Now i want to format return of those show commands, normally i am using netmiko to get the show commands.

my requirement is, i want to call this module directly inside my script and pass username/password/hostname/show command and want a return as json object.

can i call this module directly inside my script and get result as an object ? if i have to use ansible can i create playbook/inventory file dynamically and get the result.

also the script provided doesnt work on latest ansible 2.1. as ansible runner is not supported.

**Comment by compyy** [comment]
Hello,

I made  a starter, may it requires alot of fine tunning to make it more robus and scaleable.

# -*- coding: utf-8 -*-
import json
from ansible.parsing.dataloader import DataLoader
from ansible.vars import VariableManager
from ansible.inventory import Inventory
from ansible.playbook.play import Play
from ansible.executor.task_queue_manager import TaskQueueManager
from ansible.executor.playbook_executor import PlaybookExecutor
from ansible.plugins import callback_loader
from ansible.plugins.callback import CallbackBase

import os
import logging

loader = DataLoader()
variable_manager = VariableManager()
inventory = Inventory(loader=loader, variable_manager=variable_manager)
variable_manager.set_inventory(inventory)


# get result output
class ResultsCollector(CallbackBase):
    def __init__(self, *args, **kwargs):
        super(ResultsCollector, self).__init__(*args, **kwargs)
        self.host_ok = []
        self.host_unreachable = []
        self.host_failed = []

    def v2_runner_on_unreachable(self, result, ignore_errors=False):
        name = result._host.get_name()
        task = result._task.get_name()
        print(result._result)
        # self.host_unreachable[result._host.get_name()] = result
        self.host_unreachable.append(dict(ip=name, task=task, result=result))

    def v2_runner_on_ok(self, result, *args, **kwargs):
        name = result._host.get_name()
        task = result._task.get_name()
        if task == 'setup':
            pass
        elif 'Info' in task:
            self.host_ok.append(dict(ip=name, task=task, result=result))
        else:
            print(result._result['response'])
            self.host_ok.append(dict(ip=name, task=task, result=result))

    def v2_runner_on_failed(self, result, *args, **kwargs):
        name = result._host.get_name()
        task = result._task.get_name()
        print(result._result)
        self.host_failed.append(dict(ip=name, task=task, result=result))


class Options(object):
    def __init__(self):
        self.connection = 'local'
        self.forks = 10
        self.check = False
        self.become = None
        self.become_method = None
        self.become_user = None

    def __getattr__(self, name):
        return None


options = Options()


def run_adhoc(username, password, hostname, cmd, driver):
    play_source = dict(
        name='BICS  API',
        hosts=hostname,
        gather_facts='False',

        tasks=[dict(action=dict(module='ntc_show_command', args=dict(
            connection = 'ssh',
            platform = driver,
            command = cmd,
            template_dir = '/home/beta/ntc-ansible/ntc-templates/templates',
            host = hostname,
            username = username,
            password = password,
            secret = password,
        )))]
    )

    play = Play().load(play_source, variable_manager=variable_manager, loader=loader)
    tqm = None
    callback = ResultsCollector()

    try:
        tqm = TaskQueueManager(
            inventory=inventory,
            variable_manager=variable_manager,
            loader=loader,
            options=options,
            passwords=None,
            run_tree=False,
        )
        tqm._stdout_callback = callback
        result = tqm.run(play)
        return callback

    finally:
        if tqm is not None:
            tqm.cleanup()


def run_playbook(books):
    results_callback = callback_loader.get('json')
    playbooks = [books]

    variable_manager.extra_vars = {'ansible_ssh_user': 'cisco', 'ansible_ssh_pass': 'cisco'}
    callback = ResultsCollector()

    pd = PlaybookExecutor(
        playbooks=playbooks,
        inventory=inventory,
        variable_manager=variable_manager,
        loader=loader,
        options=options,
        passwords=None,

    )
    pd._tqm._stdout_callback = callback

    try:
        result = pd.run()
        return callback

    except Exception as e:
        print e


if __name__ == '__main__':
    run_adhoc('cisco', 'cisco', '192.168.124.250', 'show ip int brief', 'cisco_ios')
    # run_playbook('yml/info/process.yml')

**Comment by itdependsnetworks** [comment]
You should be able to following these directions: http://docs.ansible.com/ansible/dev_guide/developing_api.html

You are correct about 2.x no working because of ansible runner, long outstanding issue need to address and integrate with testing.

**Comment by compyy** [comment]
I already built something, and working great, you can edit, and made part of your repository.
https://github.com/compyy/BICSapp/blob/master/ansibleapi.py
