### ISSUE TITLE
AAA routers that do not require enable password to enable

### ISSUE THREAD

**Issue by jasonbarbee** [networktocode/ntc-ansible#159]
I ran into a situation where a customer had this config
"aaa authentication enable default none"

The prompt starts at Priv Level 1, and enable mode does not require a password. They are using Radius, and I think Radius is granting them permission.
 I had to modify it to get ntc_ansbile to apply config commands. Ntc_config_command module cannot handle this situation today.

I added an ansible parameter to ntc_config_command called "no_enable_password" - a boolean, including documentation note on it.
It uses the send_command_timing to ignore expect results and just type "enable" with no password for this use-case.
Once enabled, everything continues as normal. It's unusual, and NetMiko does not have a method for enabling without password at this time.

Would you be open to a PR for this setting? I realize it's a bit unusual, and up for debate on if this should be a workaround or something included in NetMiko.

Thanks,

**Comment by jedelman8** [comment]
Have you tried just supplying "\n" or a space as the enable password with netmiko (or as params in ntc_ modules) ?

**Comment by jasonbarbee** [comment]
This worked great. Tested today on IOS Catalyst routers.
secret: '\n'
I don't think we need a new parameter, but a comment in the ansible module files doc would help people think of this.
