### ISSUE TITLE
Template Cisco IOS Show version

### ISSUE THREAD

**Issue by haind13** [networktocode/ntc-ansible#160]
I add some text in template "cisco_ios_show_version.template" to show RAM and FLASH but it's shown FLASH and can not shown RAM...
How to I fix it?

> Value VERSION (.+?)
> Value ROMMON (\S+)
> Value HOSTNAME (\S+)
> Value UPTIME (.+)
> Value RUNNING_IMAGE (\S+)
> Value List HARDWARE (\S+\d\S+)
> Value List SERIAL (\S+)
> Value CONFIG_REGISTER (\S+)
> ** Value FLASH_KB (\S+)
> Value RAM_KB (\S+)**
> 
> Start
>   ^.*Software\s.+\),\sVersion\s${VERSION},*\s+RELEASE.*
>   ^ROM: ${ROMMON}
>   ^\s*${HOSTNAME}\s+uptime\s+is\s+${UPTIME}
>   ^[sS]ystem\s+image\s+file\s+is\s+"(.*?):${RUNNING_IMAGE}"
>   ^[Pp]rocessor\s+board\s+ID\s+${SERIAL}
>   ^[Cc]isco\s+${HARDWARE}.+
>   ^[Cc]onfiguration\s+register\s+is\s+${CONFIG_REGISTER}
> **  ^${FLASH_KB}\s+bytes\s+of\s+ATA
>   ^[Cc]isco\s+.+\)+\swith\s+${RAM_KB}****
>   ^Switch Port -> Stack
> 
> Stack
>   ^[Ss]ystem [Ss]erial [Nn]umber\s+:\s+${SERIAL}
>   ^[Mm]odel\s+[Nn]umber\s+:\s+${HARDWARE}\s*
>   ^[Cc]onfiguration\s+register\s+is\s+${CONFIG_REGISTER}

And I execute: 

> 
> haind@ansible:/etc/ansible$ ansible-playbook ntc_show_command.yml 
> PLAY [Test] ********************************************************************
> 
> TASK [Test] ********************************************************************
> ok: [rpgdGiangVo]
> 
> TASK [debug] *******************************************************************
> ok: [rpgdGiangVo] => {
>     "results": {
>         "changed": false, 
>         "response": [
>             {
>                 "config_register": "0x2102", 
>                 "flash_kb": "255744K", 
>                 "hardware": [
>                     "CISCO1941/K9"
>                 ], 
>                 "hostname": "rpgdGiangVo", 
>                 _**"ram_kb": "",**_ 
>                 "rommon": "System", 
>                 "running_image": "c1900-universalk9-mz.SPA.155-3.M4a.bin", 
>                 "serial": [
>                     "FGL154922NZ"
>                 ], 
>                 "uptime": "16 weeks, 1 day, 3 hours, 51 minutes", 
>                 "version": "15.5(3)M4a,"
>             }
>         ], 
>         "response_list": []
>     }
> }
> 
> PLAY RECAP *********************************************************************
> rpgdGiangVo                : ok=2    changed=0    unreachable=0    failed=0   
>

**Comment by GGabriele** [comment]
Hi @haind13 ,
can you post the raw output you're trying to parse?

**Comment by haind13** [comment]
> Cisco CISCO1941/K9 (revision 1.0) with 487424K/36864K bytes of memory.
> Processor board ID FGL154922NZ
> 6 Gigabit Ethernet interfaces
> 2 Serial(sync/async) interfaces
> 1 terminal line
> 1 Virtual Private Network (VPN) Module
> DRAM configuration is 64 bits wide with parity disabled.
> 255K bytes of non-volatile configuration memory.
> 255744K bytes of ATA System CompactFlash 0 (Read/Write)

I want to get RAM parameter and FLASH parameter in "show version" on Cisco router
I fixed template in ntc-ansible/ntc-template/templates, and execute it: Flash is show but Ram is none 
How to fix it?

**Comment by GGabriele** [comment]
Since the `Cisco CISCO1941/K9 (revision 1.0) with 487424K/36864K bytes of memory.` line is already parsed by an existing rule (`^[Cc]isco\s+${HARDWARE}.+`), you should add the regex for RAM on that line instead of adding a new one.

You can replace that line with this one: `^[Cc]isco\s+${HARDWARE}.*with\s+${RAM_KB}`

**Comment by haind13** [comment]
Thank you. 
I got it!
