### ISSUE TITLE
Error when Execute ntc_show_command

### ISSUE THREAD

**Issue by haind13** [networktocode/ntc-ansible#164]
> [root@monitornet61 ansible]# ansible-playbook ntc_show_command.yml 
> 
> PLAY [SHOW CONFIG] *************************************************************
> 
> TASK [Show Config] *************************************************************
> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios rcnGiangVo:22
> fatal: [rcnGiangVo]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_eW4Im8/ansible_module_ntc_show_command.py\", line 470, in <module>\n    main()\n  File \"/tmp/ansible_eW4Im8/ansible_module_ntc_show_command.py\", line 417, in main\n    global_delay_factor=global_delay_factor\n  File \"/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py\", line 120, in ConnectHandler\n    return ConnectionClass(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/netmiko/base_connection.py\", line 151, in __init__\n    self.establish_connection()\n  File \"/usr/lib/python2.7/site-packages/netmiko/base_connection.py\", line 505, in establish_connection\n    raise NetMikoTimeoutException(msg)\nnetmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_ios rcnGiangVo:22\n", "module_stdout": "", "msg": "MODULE FAILURE"}
>         to retry, use: --limit @/etc/ansible/ntc_show_command.retry
> 
> PLAY RECAP *********************************************************************
> rcnGiangVo                 : ok=0    changed=0    unreachable=0    failed=1 

I use ntc_show_command for test in my company but it's error! 
I test netmiko with: 

> >>> from netmiko import ConnectHandler
> 
> >>> cisco_ios = {
> ...   'device_type': 'cisco_ios',
> ...   'ip': '10.0.255.26',
> ...   'username': 'username',
> ...   'password': 'password',
> ... } 

And:

> >>> output = net_connect.send_command("show ip int brief")
> >>> print output

It's ok. 
How to fix error with ntc-ansible? 

Some information: 
I can use command: ssh username@10.0.255.26 for ssh to device
I can use python netmiko to print output 
And my device behine Firewall, I have open rule (ssh port 22)

**Comment by jedelman8** [comment]
Can you show you inventory file and playbook?

**Comment by haind13** [comment]
Playbook

> [root@monitornet61 ansible]# cat ntc_show_command.yml 
> ---
> 
> - name: SHOW CONFIG
>   hosts: cisco 
>   connection: local
>   gather_facts: False
> 
>   tasks:
>     - name: Show Config
>       ntc_show_command:
>         connection: ssh
>         platform: cisco_ios
>         template_dir: /home/haind4/ntc-ansible/ntc-templates/templates
>         command: "show version"
>         host: "{{ inventory_hostname }}"
>         username: "{{ username }}"
>         password: "{{ password }}"
>         use_templates: True 
>       register: results
> 
>     - debug: var=results.response

Inventory:

> 
> [cisco]
> rcnGiangVo host=10.0.255.26 username=username password=password

**Comment by jedelman8** [comment]
You need to update the inventory and/or task referencing the host.

Note that in your example `inventory_hostname` is `rcnGiangVo` - I'm assuming that's not an FQDN since you have `host=10.0.255.26` right next to it.  

It's also good practice to use `ansible_host`, please make the following changes:

new inventory file:

```
[cisco]
rcnGiangVo ansible_host=10.0.255.26 username=username password=password
```

and new task in the plabyook:

```
- name: Show Config
  ntc_show_command:
    connection: ssh
    platform: cisco_ios
    template_dir: /home/haind4/ntc-ansible/ntc-templates/templates
    command: "show version"
    host: "{{ ansible_host }}"   # SEE THE DIFFERENCE HERE?
    username: "{{ username }}"
    password: "{{ password }}"
    use_templates: True
  register: results
```

**Comment by haind13** [comment]
Wow, I fix it and it's working! 
Thanks @jedelman8
