### ISSUE TITLE
How do I can hide password in inventory

### ISSUE THREAD

**Issue by haind13** [networktocode/ntc-ansible#165]
I use ntc-ansible but I can not how do I can hide my password in inventory file? 
Because I have any other people to administrator network devices. 
Ansible vault just creat .yml

**Comment by itdependsnetworks** [comment]
@haind13 This is out of scope to the intention of this repo. But essentially as you stated, Ansible Vault is probably the best solution. That being said you can use `vars_prompt` or in 2.3 make use of the -u and -k flags, as shown here: https://github.com/gundalow/ansible/blob/network-debug-docs/docs/docsite/rst/network_how_tos.rst


That all being said, I would urge you to check in with ansible IRC at #ansible on irc.freenode.net or can join the ansible channel on our community slack at: slack.networktocode.com and ask questions there. They should be able to help with ansible vault issues or give a different perspective.

**Comment by haind13** [comment]
But ntc-ansible required username and password in inventory.
If I do not have this vars, it will not execute and say error:

> [root@monitornet61 ansible]# ansible-playbook ntc_show_command.yml -u admin -k

> TASK [Show Config] *************************************************************
> fatal: [rcnGiangVo]: FAILED! => {"changed": false, "failed": true, "msg": "username is required"}
