### ISSUE TITLE
junos_get_config ERROR!

### ISSUE THREAD

**Issue by haind13** [networktocode/ntc-ansible#166]
I test ntc-ansible with module junos_get_config but when I execute, it's error:

> 
> ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
> 
> The error appears to have been in '/etc/ansible/junos_get_config.yml': line 12, column 7, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> 
>     - name: GET CONFIG
>       ^ here
> 
> 
> The error appears to have been in '/etc/ansible/junos_get_config.yml': line 12, column 7, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> 
>     - name: GET CONFIG
>       ^ here

This is my playbook:

> ---
> 
> - name: SHOW CONFIG
>   hosts: junos 
>   connection: local
>   gather_facts: False
> 
>   tasks:
>     - name: OBTAIN LOGIN CREDENTIALS
>       include_vars: secrets_tuantv.yaml
> 
>     - name: GET CONFIG
>         junos_get_config:
>           host: "{{ ansible_host }}"
>           username: "{{ creds['username'] }}"
>           password: "{{ creds['password'] }}"
>           logfile: get_config.log
>           dest: "/home/haind4/junos/backup/{{ inventory_hostname }}.xml"
>           format: xml
>           #filter: "interfaces"
>           options: {inherit: inherit, groups: groups}
>        register: results
>       
>     - debug: var=results.response

How to fix it!

**Comment by GGabriele** [comment]
`junos_get_config` is not part of `ntc-ansible`. Anyway, this error is often shown when Ansible can't find the module you're trying to use. Makes sure the module called `junos_get_config` is available to Ansible.

Closing this.

**Comment by haind13** [comment]
@GGabriele What is platform for devices running Junos OS? 
Example: Cisco IOS have cisco_ios (in save_config is cisco_ios_ssh)

**Comment by GGabriele** [comment]
`juniper_junos` for ntc_show_command, `juniper_junos_netconf` for others.

**Comment by haind13** [comment]
I execute but error:

> [haind4@monitornet61 ansible]$ ansible-playbook ntc_junos_backup.yml --ask-vault-pass
>   ult password: 
> â–½
> PLAY [BACKUP CONFIGS] **********************************************************
> 
> TASK [OBTAIN LOGIN CREDENTIALS] ************************************************
> ok: [atmtest]
> 
> TASK [Save config file to backup] **********************************************
> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: jnpr.junos.exception.ConnectTimeoutError: ConnectTimeoutError(10.192.254.201)
> fatal: [atmtest]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_J3q7so/ansible_module_ntc_save_config.py\", line 256, in <module>\n    main()\n  File \"/tmp/ansible_J3q7so/ansible_module_ntc_save_config.py\", line 228, in main\n    device = ntc_device(device_type, host, username, password, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/pyntc/__init__.py\", line 35, in ntc_device\n    return device_class(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/pyntc/devices/jnpr_device.py\", line 34, in __init__\n    self.open()\n  File \"/usr/lib/python2.7/site-packages/pyntc/devices/jnpr_device.py\", line 46, in open\n    self.native.open()\n  File \"/usr/lib/python2.7/site-packages/jnpr/junos/device.py\", line 1200, in open\n    raise EzErrors.ConnectTimeoutError(self)\njnpr.junos.exception.ConnectTimeoutError: ConnectTimeoutError(10.192.254.201)\n", "module_stdout": "", "msg": "MODULE FAILURE"}
>         to retry, use: --limit @/etc/ansible/ntc_junos_backup.retry
> 
> PLAY RECAP *********************************************************************
> atmtest                    : ok=1    changed=0    unreachable=0    failed=1   

This is my playbook:

> ---
> 
> - name: BACKUP CONFIGS
>   hosts: junos
>   gather_facts: False
>   connection: local
> 
>   tasks:
>     - name: OBTAIN LOGIN CREDENTIALS
>       include_vars: secrets_tuantv.yaml
> 
>     - name: Save config file to backup
>       ntc_save_config:
>         platform: juniper_junos_netconf
>         host: "{{ ansible_host }}"
>         username: "{{ creds['username'] }}"
>         password: "{{ creds['password'] }}"
>         local_file: /home/haind4/ansible/backup/{{inventory_hostname}}.cfg
>       register: results
> 
>     - debug: var=results

**Comment by GGabriele** [comment]
`ConnectTimeoutError(10.192.254.201)` it means your device is not reachable...makes sure it is and that you're using the right credentials.

**Comment by haind13** [comment]
@GGabriele  I can ssh by command: ssh user@10.192.254.201 but execute with playbook error

**Comment by GGabriele** [comment]
Check if NETCONF port is open on the device https://www.juniper.net/techpubs/en_US/junos/topics/reference/configuration-statement/port-edit-system-services-netconf.html

**Comment by haind13** [comment]
I just config SSH (22) ? no config NETCONF port, it's can be default port (830)

**Comment by GGabriele** [comment]
Yeah, I asked to check NETCONF port on Juniper as the module uses NETCONF, not SSH.

Another thing you can do is to test Juniper PyEZ API and see if it works.

Again, due to the error it doesn't seem to be an issue related to ntc-ansible.
