### ISSUE TITLE
ntc_show_command - Make host, username, password optional?

### ISSUE THREAD

**Issue by refriedjello** [networktocode/ntc-ansible#167]
Is there a way to make some arguments to ntc_show_command module optional?

I ask because I am running playbooks from Rundeck with the plugin rundeck-ansible-plugin from Batix, and all connection/authentication parameters get fed from there.

So a entire playbook using the ios_command module looks like this:

> ---
> - name: Show VLAN
>   hosts: all
> 
>   tasks:
> 
>     - name: Show VLAN
>       ios_command:
>         commands:
>           - show vlan
> 

Using the ntc_show_command module the same playbook looks like this:

> ---
> - name: Show VLAN
>   hosts: all
> 
>   tasks:
>     - ntc_show_command:
>         host: "{{ inventory_hostname }}"
>         username: netadmin
>         password: supersecret
>         connection: ssh
>         platform: cisco_ios
>         command: 'show vlan'
>         template_dir: /etc/ansible/modules/ntc-ansible/ntc-templates/templates/

Looking to streamline/standardize how my jobs in Rundeck are defined, and leverage the password vault it has, but also looking to take advantage of the improved output parsing that NTC modules provide.

Thanks!

**Comment by itdependsnetworks** [comment]
We can look into ansible_host, ansible_user, and ansible_password. However, platform for example will be required, since the module is vendor independent.

**Comment by jeffkala** [comment]
stale, please retest now that 1.0.0 of the collection is out.
