### ISSUE TITLE
"This module requires TextFSM"

### ISSUE THREAD

**Issue by wilmington** [networktocode/ntc-ansible#169]
Looks like multiple people have reported this in the closed issue https://github.com/networktocode/ntc-ansible/issues/94

I'm on Ubuntu 16.04.1 LTS. Python 2.7.12, Running in a virtualenv.

All packages present, can import all the modules into python. On running a play I see 

`FAILED!` => {"changed": false, "failed": true, "msg": "This module requires `TextFSM"}`

issue exists with ansible 2.2 and 2.3 and with pip or manually installed gtextfsm

**Comment by wilmington** [comment]
Success on a fresh Ubuntu 16.04.1 LTS. Python 2.7.12 build running without a virtualenv.  Checking configuration of virtualenv - will attempt to reproduce.

**Comment by jmorello12** [comment]
I have the same issue in a virtualenv with:
python 2.7.12
ansible 2.3.1.0
terminal 0.4.0
gtextfsm 0.2.1 (from pip)
textfsm 0.3.2 (from git, installed with python setup.py)
ntc-ansible 0.1.0

**Comment by itdependsnetworks** [comment]
I have updated the readme, but basically this usually happens (especially in virtualenvs) if you do not have ansible_python_interpreter set. Take a look at the Readme and follow those instructions, if that doesn't help, let us know.

**Comment by wilmington** [comment]
My issue solved by adding this to my inventory
```
[all:vars]
ansible_python_interpreter="/usr/bin/env python"
```

**Comment by GGabriele** [comment]
Awesome!
