### ISSUE TITLE
cisco_ios_show_interfaces_status.template skipping over err-disabled interface

### ISSUE THREAD

**Issue by GithubRandomUser** [networktocode/ntc-ansible#172]
I have noticed that in the following situation the cisco_ios_show_interfaces_status.template will skip over the interface G1/3 because its in the err-disabled state. I believe the template needs to be updated to "Value STATUS ([\w-]+)"
#sh int statu
Port      Name               Status       Vlan       Duplex  Speed       Type
Gi1/1                        connected    41         a-full a-1000 10/100/1000-TX
Gi1/2                        connected    41         a-full a-1000 10/100/1000-TX
Gi1/3                        err-disabled 41           auto   auto 10/100/1000-TX
Gi1/4                        connected    41         a-full a-1000 10/100/1000-TX

**Comment by GGabriele** [comment]
Hey,

I've just pushed a commit to fix that. Thanks.
