### ISSUE TITLE
Dealing with inconsistencies with Cisco command output (NXOS)

### ISSUE THREAD

**Issue by gavmckee80** [networktocode/ntc-ansible#179]
Is there a way in the template definition to handle slight difference in the output between one model of Cisco switch and another?  Cisco drive me completely nuts with the inconsistency across platforms even running the same OS type. 
"Nexus7700 C7706 (6 Slot) Chassis "

```
XXXXXXXX# show interface mgmt0
mgmt0 is up
admin state is up
  Hardware: GigabitEthernet, address: 84b5.17f5.e0a4 (bia 84b5.17f5.e0a4)
  Description: ->xxxxxxxx  Gi2/37
  Internet Address is 10.32.209.100/24
  MTU 1500 bytes, BW 1000000 Kbit, DLY 10 usec
  reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, medium is broadcast
  Port mode is routed
  full-duplex, 1000 Mb/s
  Auto-Negotiation is turned on
  Auto-mdix is turned off
  EtherType is 0x0000 
  1 minute input rate 688 bits/sec, 0 packets/sec
  1 minute output rate 512 bits/sec, 0 packets/sec
  Rx
    7334743 input packets 3455961 unicast packets 2270083 multicast packets
    1608699 broadcast packets 1040081447 bytes
  Tx
    3784951 output packets 3462525 unicast packets 322419 multicast packets
    7 broadcast packets 840321133 bytes
```

Parsing this using NTC show command
ok: [xxxxxxxxx] => (item={u'hardware_type': u'GigabitEthernet', u'description': u'->xxxxxxxx Gi2/37', u'link_status': u'up', u'duplex': u'full-duplex', u'ip_address': u'10.32.209.100/24', u'bia': u'84b5.17f5.e0a4', u'delay': u'10 usec', u'bandwidth': u'1000000 Kbit', u'admin_state': u'', u'address': u'84b5.17f5.e0a4', u'interface': u'mgmt0', u'encapsulation': u'ARPA', u'mtu': u'1500', u'speed': u'1000 Mb/s'}) => {
    "item": {
        "address": "84b5.17f5.e0a4", 
        "admin_state": "", 
        "bandwidth": "1000000 Kbit", 
        "bia": "84b5.17f5.e0a4", 
        "delay": "10 usec", 
        "description": "->xxxxxxxxxx Gi2/37", 
        "duplex": "full-duplex", 
        "encapsulation": "ARPA", 
        "hardware_type": "GigabitEthernet", 
        "interface": "mgmt0", 
        "ip_address": "10.32.209.100/24", 
        "link_status": "up", 
        "mtu": "1500", 
        "speed": "1000 Mb/s"
    }, 
    "msg": "mgmt0"

"Nexus 6004 Chassis"
```
XXXXXXXX# show interface mgmt0
mgmt0 is up

  Hardware: GigabitEthernet, address: 002a.6a66.95c1 (bia 002a.6a66.95c1)
  Internet Address is 10.70.253.251/24
  MTU 1500 bytes,  BW 1000000 Kbit,, BW 1000000 Kbit, DLY 10 usec
  reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, medium is broadcast
  full-duplex, auto-speed
  EtherType is 0x0000 
  Rx
    29313313 input packets 2940919202 bytes
    5543899 unicast packets 19957172 multicast packets
    3812242 broadcast packets  2 packets/sec
    1 minute input rate 2240 bits/sec
  Tx
    6402594 output packets 1208190919 bytes
    5547495 unicast packets 855097 multicast packets
    2 broadcast packets  1 packets/sec
    1 minute output rate 1328 bits/sec
```

Parsing this using NTC show command
ok: [xxxxxxxxx] => (item={u'hardware_type': u'', u'description': u'', u'link_status': u'up', u'duplex': u'', u'ip_address': u'', u'bia': u'', u'delay': u'', u'bandwidth': u'', u'admin_state': u'', u'address': u'', u'interface': u'mgmt0', u'encapsulation': u'', u'mtu': u'', u'speed': u''}) => {
    "item": {
        "address": "", 
        "admin_state": "", 
        "bandwidth": "", 
        "bia": "", 
        "delay": "", 
        "description": "", 
        "duplex": "", 
        "encapsulation": "", 
        "hardware_type": "", 
        "interface": "mgmt0", 
        "ip_address": "", 
        "link_status": "up", 
        "mtu": "", 
        "speed": ""
    }, 
    "msg": "mgmt0"
}

**Comment by itdependsnetworks** [comment]
Can you track this issue within ntc-templates: https://github.com/networktocode/ntc-templates
