### ISSUE TITLE
Issue when using ntc_file_copy

### ISSUE THREAD

**Issue by nncse** [networktocode/ntc-ansible#181]
Hi,

I was wondering if somebody could provide some help on an issue I ran into when using ntc_file_copy.  My goal is to login to a Cisco switch, check if it is not running a particular image and scp the image from my server to the device. Basically, I tried to test the functionality that was created/done by "http://anastarsha.com/automating-cisco-device-upgrades-with-ansible/" but I am unsuccessful so far:

Below is my config:

  tasks:
    - name: GATHER FACTS
      ios_facts:
        gather_subset: hardware
        provider: "{{ credentials }}"
      register: hardware_ios_s
      tags: facts_ios_s

    - name: TEST WHEN FUNCTION
      ntc_file_copy:
        platform: cisco_ios_ssh
        local_file: /home/nncse/Downloads/cat4500e-entservicesk9-mz.152-2.E7.bin
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
      when: hardware_ios_s.ansible_facts != '152-2.E7'

Below is the error that I received:

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_tnac_r/ansible_module_ntc_file_copy.py", line 262, in <module>
    main()
  File "/tmp/ansible_tnac_r/ansible_module_ntc_file_copy.py", line 237, in main
    remote_exists = device.file_copy_remote_exists(local_file, remote_file)
  File "/usr/local/lib/python2.7/dist-packages/pyntc-0.0.5-py2.7.egg/pyntc/devices/ios_device.py", line 141, in file_copy_remote_exists
    if fc.check_file_exists() and fc.compare_md5():
  File "/usr/local/lib/python2.7/dist-packages/netmiko/scp_handler.py", line 132, in check_file_exists
    raise ValueError("Unexpected output from check_file_exists")
ValueError: Unexpected output from check_file_exists

fatal: [c4948e_2]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "ntc_file_copy"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_tnac_r/ansible_module_ntc_file_copy.py\", line 262, in <module>\n    main()\n  File \"/tmp/ansible_tnac_r/ansible_module_ntc_file_copy.py\", line 237, in main\n    remote_exists = device.file_copy_remote_exists(local_file, remote_file)\n  File \"/usr/local/lib/python2.7/dist-packages/pyntc-0.0.5-py2.7.egg/pyntc/devices/ios_device.py\", line 141, in file_copy_remote_exists\n    if fc.check_file_exists() and fc.compare_md5():\n  File \"/usr/local/lib/python2.7/dist-packages/netmiko/scp_handler.py\", line 132, in check_file_exists\n    raise ValueError(\"Unexpected output from check_file_exists\")\nValueError: Unexpected output from check_file_exists\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}

Thank you in advance.

**Comment by GGabriele** [comment]
Hi @nncse ,
can you post the output you get from running `dir flash:` and `dir flash:/cat4500e-entservicesk9-mz.152-2.E7.bin` commands?

**Comment by nncse** [comment]
Hi Gabriel,

Here are the results:
```
c4948e_2#dir bootflash:
Directory of bootflash:/

    6  -rw-    27242762  Nov 14 2014 17:21:30 -05:00  cat4500e-entservicesk9-mz.150-2.SG8.bin

128282624 bytes total (90959872 bytes free)
c4948e_2#dir bootflash:cat4500e-entservicesk9-mz.152-2.E7.bin
%Error opening bootflash:/cat4500e-entservicesk9-mz.152-2.E7.bin (File not found)
```

**Comment by GGabriele** [comment]
Can you add explicitly the `file_system ` into the task like this?

```
- name: TEST WHEN FUNCTION
  ntc_file_copy:
    platform: cisco_ios_ssh
    local_file: /home/nncse/Downloads/cat4500e-entservicesk9-mz.152-2.E7.bin
    host: "{{ inventory_hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    file_system: "bootflash"
  when: hardware_ios_s.ansible_facts != '152-2.E7'
```

**Comment by nncse** [comment]
It is now showing a different error.
```
fatal: [c4948e_2]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "file_system": "bootflash", 
            "host": "c4948e_2", 
            "local_file": "/home/nncse/Downloads/cat4500e-entservicesk9-mz.152-2.E7.bin", 
            "ntc_conf_file": null, 
            "ntc_host": null, 
            "password": "", 
            "platform": "cisco_ios_ssh", 
            "port": null, 
            "remote_file": null, 
            "secret": null, 
            "transport": null, 
            "username": "admin"
        }, 
        "module_name": "ntc_file_copy"
    }, 
    "msg": "FileTransferError: \nAn error occured during transfer. Please make sure the local file exists and that appropriate permissons are set on the remote device."
```

**Comment by GGabriele** [comment]
That's better :)

Can you try to manually scp your file to the device?

**Comment by nncse** [comment]
Yep, I am trying that now.

**Comment by nncse** [comment]
I can manually upload the file from my server where Ansible/ntc-ansible is running from.
```
nncse@e7ch1glmf01:~/Downloads$ scp cat4500e-entservicesk9-mz.152-2.E7.bin admin@c4948e_2:/cat4500e-entservicesk9-mz.152-2.E7.bin
Password: 
cat4500e-entservicesk9-mz.152-2.E7.bin                                                                                                                                                                                                                                                  2% 1056KB   5.4KB/s 1:56:42 ETA
```

**Comment by GGabriele** [comment]
Closing this, solved offline with @nncse , the issue was a missing colon on file system param: `bootflash:`

**Comment by nncse** [comment]
file transfer issue resolved by adding ":" after bootflash in file_system: Thanks Gabriel.
