### ISSUE TITLE
Add SFTP support to ntc_file_copy

### ISSUE THREAD

**Issue by kadecole** [networktocode/ntc-ansible#186]
The network switches I use require SFTP to copy the software onto the device. I was wondering if it was possible to expand the ntc_file_copy module to include using the `sftp put` command to place software on the remote network switch.

**Comment by itdependsnetworks** [comment]
Which network switch is this?

**Comment by kadecole** [comment]
I am using Extreme (Avaya) VSP switches. They only support SFTP and not SCP.

**Comment by itdependsnetworks** [comment]
This relies on pyntc, you are welcome to put in a PR to accomplish this, the constructs already deployed should make it make easier to build the extension, e.g. you can follow what was done in other drivers and largely copy paste. 

That being said there is currently no plans to support this.
