### ISSUE TITLE
No access to priviledged mode when using telnet on cisco switches

### ISSUE THREAD

**Issue by ifleg** [networktocode/ntc-ansible#189]
Hello,
Using telnet I cannot enter in priviledged mode (enable) on cisco switches.
I try to use the ntc_show_command (because ntc_save_config does not support telnet)

Here is the interresting part of the playbook:
It works with ssh but not with telnet  nor netmiko_telnet.

    - name: Backup
      ntc_show_command:
        connection: telnet
        platform: cisco_ios
        use_templates: false
        provider: "{{ provider }}"
        command: "show run"
        local_file: "/path_to_backup/{{ inventory_hostname }}.cfg"

Any clue ?

**Comment by itdependsnetworks** [comment]
What does your provider look like?

**Comment by jeffkala** [comment]
closing. Please retest now that #268 is deployed and 1.0.0 of this collection is in ansible-galaxy now.
