### ISSUE TITLE
HP show running not working

### ISSUE THREAD

**Issue by sppwf** [networktocode/ntc-ansible#198]
Hi Team,

So, the issues might be strange, however the issues is here. 
using next config
  tasks:
  - name: show config
    ntc_show_command:
      command: "show config"
      connection: ssh
      platform: hp_procurve
      template_dir: "/home/vagrant/projects/ntc-ansible/ntc-templates/templates"
      host: "{{ inventory_hostname }}"
      username: "{{ cli.username }}"
      password: "{{ cli.password }}"
    register: show_run

  - name: show_run
    debug:
      msg: "{{ show_run.response[0] }}"

Host - HP Switch
VE-HQ-CORE-SW1# sh lldp info local-device 

 LLDP Local Device Information

  Chassis Type : mac-address      
  Chassis Id   : 1c 98 ec ae 82 00        
  System Name  : CORE-SW1                  
  System Description : HP J9851A Switch 5412Rzl2, revision KB.16.02.0016, R...
  System Capabilities Supported: bridge, router
  System Capabilities Enabled: bridge, router

Command does not want to retrive running config for this switch. 
it works for other switches - 2920 HPs, however it does not want to take the config for this specific platform - 5412. It might be that it has bigger config, i do not know.

Output:
TASK [show config] ******************************************************************************************************************************************************************************************
task path: /home/vagrant/infrastructure/ansible/cisco/playbooks/hp_backup.yml:21
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/basic.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/_text.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/six/__init__.py
Using module file /home/vagrant/projects/ntc-ansible/library/ntc_show_command.py
<10.162.15.240> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<10.162.15.240> EXEC /bin/sh -c 'echo ~ && sleep 0'
<10.162.15.240> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1521232784.7-201299282934334 `" && echo ansible-tmp-1521232784.7-201299282934334="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1521232784.7-201299282934334 `" ) && sleep 0'
<10.162.15.240> PUT /tmp/tmpLMNm75 TO /home/vagrant/.ansible/tmp/ansible-tmp-1521232784.7-201299282934334/ntc_show_command.py
<10.162.15.240> EXEC /bin/sh -c 'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1521232784.7-201299282934334/ /home/vagrant/.ansible/tmp/ansible-tmp-1521232784.7-201299282934334/ntc_show_command.py && sleep 0'
<10.162.15.240> EXEC /bin/sh -c '/usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1521232784.7-201299282934334/ntc_show_command.py; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1521232784.7-201299282934334/" > /dev/null 2>&1 && sleep 0'
ok: [10.162.15.240] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "command": "show config", 
            "connection": "ssh", 
            "connection_args": {}, 
            "delay": "1", 
            "file": null, 
            "global_delay_factor": "1", 
            "host": "10.162.15.240", 
            "index_file": "index", 
            "key_file": null, 
            "local_file": null, 
            "optional_args": {}, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "platform": "hp_procurve", 
            "port": null, 
            "provider": null, 
            "secret": null, 
            "template_dir": "/home/vagrant/projects/ntc-ansible/ntc-templates/templates", 
            "trigger_device_list": null, 
            "use_keys": false, 
            "use_templates": true, 
            "username": "cisco_admin"
        }
    }, 
    "response": [], 
    "response_list": []
}

TASK [show_run] **********************************************************************************************************************************************************************************************
task path: /home/vagrant/infrastructure/ansible/cisco/playbooks/hp_backup.yml:32
fatal: [10.162.15.240]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: list object has no element 0\n\nThe error appears to have been in '/home/vagrant/infrastructure/ansible/cisco/playbooks/hp_backup.yml': line 32, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: show_run\n    ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: list object has no element 0"
}

PLAY RECAP ***************************************************************************************************************************************************************************************************
10.162.15.240              : ok=4    changed=0    unreachable=0    failed=1   

What do you think?

Thanks
Sergiu Plotnicu

**Comment by sppwf** [comment]
It works if i "show version" for same switch

**Comment by sppwf** [comment]
found issues 
was supposed to put "delay: 5"

**Comment by jmcgill298** [comment]
Closing per comment that it is resolved
