### ISSUE TITLE
Problem with file size - ntc_file_copy

### ISSUE THREAD

**Issue by AlfredoSangiuliano** [networktocode/ntc-ansible#200]
I'm trying to upload a new IOS version in my routers, y get an error msg. 

In order to troubleshoot the problem y try to copy a smaller file (13MB aprox), **and the transfer run OK.** But copying the image (450M), the task drop the error. 
Also try the same filename but smaller and the transfer run OK. The problem seems to be related to the file size...  

[root@srappl001v052 ansible]# ansible --version
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/applications/ansible/my_modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Nov 21 2017, 10:46:38) [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
[root@srappl001v052 ansible]# python -V
Python 2.7.10
[root@srappl001v052 ansible]# ansible-playbook upgrade_ios.yml
SSH password:

PLAY [---- Cambio de redes de sucursales ----] ***************************************************************************************************

TASK [Ver datos del equipo] **********************************************************************************************************************
ok: [10.9.1.18]

**TASK [Copiando Imagen] ***************************************************************************************************************************
fatal: [10.9.1.18]: FAILED! => {"changed": false, "failed": true, "msg": "FileTransferError: \nAn error occured during transfer. Please make sure the local file exists and that appropriate permissons are set on the remote device."}
        to retry, use: --limit @/applications/ansible/upgrade_ios.retry**

PLAY RECAP ***************************************************************************************************************************************
10.9.1.18                  : ok=1    changed=0    unreachable=0    failed=1

[root@srappl001v052 ansible]#

**Comment by hazelfire5** [comment]
You should first try and look to see how much space you have available on the router by running a 'dir' on the filesystem you are transferring to. You should validate there is enough space available for the entire file. While you are transferring the file, you should sit on a ssh connection and continue to type 'dir' to see the increase of the file size. Try to delete any unneeded .bin files from there to see if that helps.

**Comment by AlfredoSangiuliano** [comment]
Thank you very much for the contribution hazelfire5. It is checked that there is enough space available in the Router. In fact, the transfer by CLI with the "copy" command works well.

**Comment by jmcgill298** [comment]
#242
