### ISSUE TITLE
How can I pull this package on my offline server

### ISSUE THREAD

**Issue by chopha66** [networktocode/ntc-ansible#201]
Hello. I'm trying to automate and get data of network device. 
I'm interested in ntc-ansible package. 
But my ansible control server is not connected internet, because of security(it's in the company)
I really want to use this package, How can I pull this on my offline server.
The server is REDHAT OS , and ansible version is 2.4.3

**Comment by OzNetNerd** [comment]
1. [Download the code](https://github.com/networktocode/ntc-ansible.git) on a PC which does have internet connectivity.
2. Copy the code onto the Ansible box.
3. Move the directories to their appropriate locations. (I [blogged about this](http://www.oznetnerd.com/installing-ntc-ansible/) some time ago. The information there should still be relevant/correct.)

**Comment by jmcgill298** [comment]
Answered above
