### ISSUE TITLE
FAILED! This module requires netmiko

### ISSUE THREAD

**Issue by haind13** [networktocode/ntc-ansible#206]
Hi all
I create playbook and execute it. But this have ERROR

> fatal: [rpgdCrownOffice]: FAILED! => {"changed": false, "msg": "This module requires netmiko."}

I install ansible and ntc-ansible same as tutorial

**Comment by haind13** [comment]
I checked pip list and seen netmiko :-? 

[root@monitornet61 ansible]# pip list | grep netmiko
netmiko                          2.1.1

Anyone help you fix this error

**Comment by jmcgill298** [comment]
Can you provide the output of `ansibke --version`?

**Comment by haind13** [comment]
This is my ansible version

> [root@monitornet61 ansible]# ansible --version
> ansible 2.4.2.0
>   config file = /etc/ansible/ansible.cfg
>   configured module search path = [u'/data/ansible']
>   ansible python module location = /usr/lib/python2.7/site-packages/ansible
>   executable location = /usr/bin/ansible
>   python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

**Comment by haind13** [comment]
After I removed gss it's working normally!
