### ISSUE TITLE
ntc_show_commands default template directory wrong

### ISSUE THREAD

**Issue by jspruyt** [networktocode/ntc-ansible#210]
According to documentation, the default template directory should be 'ntc-templates/templates' (which is also the path in the repo). 
In the ntc_show_commands.py code however, the default template directory is set to 'ntc_templates/templates' with underscore instead of dash.

**Comment by jeffkala** [comment]
closing. Please retest now that #268 is deployed and 1.0.0 of this collection is in ansible-galaxy now.
