### ISSUE TITLE
Support for IOS XE INSTALL mode

### ISSUE THREAD

**Issue by Noname2244** [networktocode/ntc-ansible#212]
Will we see support for INSTALL mode in the install_os command?

**Comment by Noname2244** [comment]
There will probably not be any support since there is so many different installations modes, bundle to install different syntax for different track 16.3 16.6 etc

**Comment by jeffkala** [comment]
closing. Please retest now that #268 is deployed and 1.0.0 of this collection is in ansible-galaxy now.
