### ISSUE TITLE
ntc_install_os updates boot variable only on primary switch in stack

### ISSUE THREAD

**Issue by m0ps** [networktocode/ntc-ansible#217]
I have a few c2960x stacks and I wrote a playbook that upgrades IOS on it. But while I set a boot variable via ntc_install_os it updates it only on primary switch, all other stack members left untouched. Is there a chance that this function will be added in a near future, or is there any workaround can be applied?

**Comment by OzNetNerd** [comment]
Can you please provide your playbook? It will aid in troubleshooting and fixing the issue.

**Comment by m0ps** [comment]
tasks:
  - name: "COPYING IMAGE TO flash1:"
    ntc_file_copy:
      platform: cisco_ios_ssh
      file_system: "flash1:"
      local_file: "images/{{ target_image }}"
      remote_file: "{{ target_image }}"
      host: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
    notify:
      - SET BOOT VARIABLE

  - name: "COPYING IMAGE TO flash2:"
    ntc_file_copy:
      platform: cisco_ios_ssh
      file_system: "flash2:"
      local_file: "images/{{ target_image }}"
      remote_file: "{{ target_image }}"
      host: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
    notify:
      - SET BOOT VARIABLE

  handlers:
  - name: "SET BOOT VARIABLE"
    ntc_install_os:
      platform: cisco_ios_ssh
      host: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      system_image_file: "{{ target_image }}"

It looks like ntc_install_os execute:
boot system <pathlist of boot file>
But when switches are stacked, it must execute:
boot system switch all <pathlist of boot file>

C2960X-STACK1(config)#boot system ?      
  WORD    pathlist of boot file(s) ... file1;file2;...
  switch  Set system image for switches in the stack
C2960X-STACK1(config)#boot system switch ?   
  <1-8>  Switch number
  all    Set system image for all switches in the stack

**Comment by Ondjultomte** [comment]
Is this solved?

**Comment by FragmentedPacket** [comment]
This is not solved within our modules. It does look like there is some work to do within `pyntc` and these modules to add support for that.

**Comment by jeffkala** [comment]
closing. Please retest now that #268 is deployed and 1.0.0 of this collection is in ansible-galaxy now. Logic itself should be in pyntc.
