### ISSUE TITLE
ntc-ansible can use with ansible awx

### ISSUE THREAD

**Issue by haind13** [networktocode/ntc-ansible#218]
Hi,
Now I'm setting Ansible Awx. Can I have use ntc-ansible for it?

**Comment by timaklnz** [comment]
sudo docker exec -it <container-id> /bin/bash
<awx-task># pip install ntc-ansible

**Comment by jmcgill298** [comment]
You can copy the ntc-ansible modules in your [DEFAULT_MODULE_PATH](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-module-path) directory and ensure that the AWX python environment has the necessary python libraries installed.
