### ISSUE TITLE
I am running this adhoc command to run a script to start Informatica services using ansible

### ISSUE THREAD

**Issue by sudgay** [networktocode/ntc-ansible#223]
The command:
ansible informatica_dev -i inventory1 -m shell -a "/opt/Informatica/9.5.1/tomcat/bin/infaservice.sh startup"

The command works and gives me a success see.
caexvd0014.upc | SUCCESS | rc=0 >>
Starting Informatica services on node 'DEV_caexvd0014'
Using CURRENT_DIR:     /opt/Informatica/9.5.1/tomcat/bin
Using INFA_HOME:       /opt/Informatica/9.5.1

When I check the remote server for tomcat startup. I find that tomcat has not started.

I have also used:
ansible informatica_dev -i inventory1 -m shell -a "chdir=/opt/Informatica/9.5.1/tomcat/bin/ sh infaservice.sh startup" 
and
informatica_dev -i inventory1 -m command -a "/opt/Informatica/9.5.1/tomcat/bin/infaservice.sh startup" -vvv

but tomcat does not start on the remote server. How do I solve this and get Informatica services to start.

Will appreciate the help.

Sudhir

**Comment by jmcgill298** [comment]
This is not related to this project; please reach out to the maintainers of the imformatica_dev module
