### ISSUE TITLE
FileTransferError ntc_file_copy

### ISSUE THREAD

**Issue by gittyguy** [networktocode/ntc-ansible#240]
Hello,
I'm trying to copy a bin file to a 2960X stack with 2 members. 
ansible-doc is returning output, flash drive has enough space, scp from the Ansilbe machine is working, ntc_file_copy is working when I don't specify a remote_file.
But I want to upload the bin file to flash1: and afterwards to flash2:
Is there a raison why flash1: & flash2 are not accepted in the remote_file parameter ?
Thanks in advance.

Task: 
    ntc_file_copy:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      platform: cisco_ios_ssh
      local_file: "/home/guy/Ansible/images/{{ new_image }}"
      remote_file: "flash{{ item }}:"
    vars:
      ansible_command_timeout: 600
    when: "(not(new_image in flash.stdout[0])) and (freespace|int > imagebytes|int)"
    loop: "{{ members }}"

-vvvv output :
<192.168.88.10> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/guy/.ansible/tmp/ansible-local-14467v6ubd_/ansible-tmp-1552418396.03-157189299543452 `" && echo ansible-tmp-1552418396.03-157189299543452="` echo /home/guy/.ansible/tmp/ansible-local-14467v6ubd_/ansible-tmp-1552418396.03-157189299543452 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/napalm_ansible/modules/ntc-ansible/library/ntc_file_copy.py
<192.168.88.10> PUT /home/guy/.ansible/tmp/ansible-local-14467v6ubd_/tmpfvEMeZ TO /home/guy/.ansible/tmp/ansible-local-14467v6ubd_/ansible-tmp-1552418396.03-157189299543452/AnsiballZ_ntc_file_copy.py
<192.168.88.10> EXEC /bin/sh -c 'chmod u+x /home/guy/.ansible/tmp/ansible-local-14467v6ubd_/ansible-tmp-1552418396.03-157189299543452/ /home/guy/.ansible/tmp/ansible-local-14467v6ubd_/ansible-tmp-1552418396.03-157189299543452/AnsiballZ_ntc_file_copy.py && sleep 0'
<192.168.88.10> EXEC /bin/sh -c '/usr/bin/python /home/guy/.ansible/tmp/ansible-local-14467v6ubd_/ansible-tmp-1552418396.03-157189299543452/AnsiballZ_ntc_file_copy.py && sleep 0'
<192.168.88.10> EXEC /bin/sh -c 'rm -f -r /home/guy/.ansible/tmp/ansible-local-14467v6ubd_/ansible-tmp-1552418396.03-157189299543452/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_ntc_file_copy_payload_ScmyKn/__main__.py", line 307, in main
    device.file_copy(local_file, remote_file)
  File "/usr/local/lib/python2.7/dist-packages/pyntc/devices/ios_device.py", line 221, in file_copy
    raise FileTransferError
failed: [teststack] (item=2) => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "delay_factor": 1, 
            "file_system": null, 
            "global_delay_factor": 1, 
            "host": "192.168.88.10", 
            "local_file": "/home/guy/Ansible/images/c2960x-universalk9-mz.152-6.E2.bin", 
            "ntc_conf_file": null, 
            "ntc_host": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "platform": "cisco_ios_ssh", 
            "port": null, 
            "provider": null, 
            "remote_file": "flash2:", 
            "secret": null, 
            "transport": null, 
            "username": "cisco"
        }
    }, 
    "item": "2", 
    "msg": "FileTransferError: \nAn error occurred during transfer. Please make sure the local file exists and that appropriate permissions are set on the remote device."

**Comment by jmcgill298** [comment]
I think you are looking to use `file_system` and not `remote_file`. The `file_system` command allows you to specify where the file gets placed on the network device, and defaults to the whatever the system uses as a default (what is output when you type `dir` on the switch). The `remote_file` parameter allows you to specify the name of the file if you would like to use a different name than the `local_file` option.

If you specify the `file_system` as `flash1:` and `flash2:` and do not pass anything for `remote_file`, I believe you will get the results you are looking for.

**Comment by gittyguy** [comment]
Hello, 
Thank you very much !!! I didn't know of that parameter :(... I was looking at the following link https://ntc-docs.readthedocs.io/en/latest/ntc-ansible%20Modules%20(multi-vendor)/ntc_file_copy_module.html
