### ISSUE TITLE
Problem with the option "register" when using ntc_show_command

### ISSUE THREAD

**Issue by HouriaH** [networktocode/ntc-ansible#241]
**My playbook:**

   - name: Connexion aux switchs en Telnet
     hosts: switchs-Telnet
     gather_facts: no
     connection: local

     tasks:

      - name: Connexion sur les switchs et envoi de commandes
        ntc_show_command:
            connection: 'telnet'
            platform: 'cisco_ios'
            port: 23
            command:
              - show running-config
            host: "{{ host }}"
            username: "{{ username }}"
            password: "{{ password }}"
            secret: "{{ password_enable }}"
            #global_delay_factor: 4
            template_dir: /etc/ansible/playbooks/ntc-ansible/ntc-templates/templates/
        register: config1

      - name: Copy de la conf
        copy:
            content: "{{ config1.stdout[0] }}"
            dest: "/etc/ansible/backups/show_run_{{ inventory_hostname }}_{{ host }}.txt"
        register: copy

**The error :** 

PLAY [Connexion aux switchs en Telnet] ****************************************************************************************************************************************************************

TASK [Connexion sur les switchs et envoi de commandes] ************************************************************************************************************************************************
ok: [LDE-13-ISTR-002_SW-3]

TASK [Copy de la conf] ********************************************************************************************************************************************************************************
fatal: [LDE-13-ISTR-002_SW-3]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/etc/ansible/playbooks/backup_cisco_switch2.yaml': line 56, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n      - name: Copy de la conf\n        ^ here\n"}
        to retry, use: --limit @/etc/ansible/playbooks/backup_cisco_switch2.retry

**Conclusion:** 

It seems like I can't use my register: config1 for the copy task.
Can you help me to figure out what is the problem please.

**Comment by jmcgill298** [comment]
The register is working fine; the error indicates that `config1` does not have an attribute `stdout`. The `ntc_show_command` returns the following:
- changed
- failed
- response
- response_list

**Comment by HouriaH** [comment]
Thank you for your answer.
I would like to recover the switch configuration and to put it on a file that's why I used the register. Will it be possible to do that with the ntc_show_command or I have to use something else ?

**Comment by jmcgill298** [comment]
I would recommend running a debug task to see the output of the registered variable.

```
- name: Connexion aux switchs en Telnet
  hosts: switchs-Telnet
  gather_facts: no
  connection: local
  tasks:
    - name: Connexion sur les switchs et envoi de commandes
      ntc_show_command:
        connection: 'telnet'
        platform: 'cisco_ios'
        port: 23
        command: 'show running-config'
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        secret: "{{ password_enable }}"
        #global_delay_factor: 4
        template_dir: /etc/ansible/playbooks/ntc-ansible/ntc-templates/templates/
      register: config1

    - debug:
         var: "config1"
```

You should see a dictionary with the 4 values listed above. I believe you would want to use `config1["response"]`

**Comment by HouriaH** [comment]
Thank you I used config1["response"] and it works !
