### ISSUE TITLE
Socket Closed with ntc_file_copy

### ISSUE THREAD

**Issue by gittyguy** [networktocode/ntc-ansible#242]
I'm trying to upload an IOS image to 2960X stack with 2 physical switches.
First switch is going fine, second gives a 'Socket is closed' error.
I've tried to raise the timeout with 'ansible_command_timeout' but is not applicable apparently becuase pyntc is used to connect.
Ansible is running on VMWare machine
Ansible version:
  ansible 2.7.7
  config file = /home/guy/Ansible/playbooks/access/iosupgrade/ansible.cfg
  configured module search path = [u'/usr/local/lib/python2.7/dist-packages/napalm_ansible/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /home/guy/.local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
ntc_file_copy configuration:
    - name: "Copy boot image on all members in the stack"
      ntc_file_copy:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        platform: cisco_ios_ssh
        local_file: "/home/guy/Ansible/images/{{ new_image }}"
        file_system: "flash{{ item }}:"
      vars:
        ansible_command_timeout: 900
      when: "(not(new_image in flash.stdout[0])) and (freespace|int > imagebytes|int)"
      loop: "{{ members }}"

Output traceback:
************
TASK [Copy boot image on all members in the stack] **************************************************************
task path: /home/guy/Ansible/playbooks/access/iosupgrade/imagecopy.yml:2
<99.99.99.99> ESTABLISH LOCAL CONNECTION FOR USER: root
<99.99.99.99> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/guy/.ansible/tmp/ansible-local-18577FekORD/ansible-tmp-1552586644.8-88084817997960 `" && echo ansible-tmp-1552586644.8-88084817997960="` echo /home/guy/.ansible/tmp/ansible-local-18577FekORD/ansible-tmp-1552586644.8-88084817997960 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/napalm_ansible/modules/ntc-ansible/library/ntc_file_copy.py
<99.99.99.99> PUT /home/guy/.ansible/tmp/ansible-local-18577FekORD/tmpQlz1uX TO /home/guy/.ansible/tmp/ansible-local-18577FekORD/ansible-tmp-1552586644.8-88084817997960/AnsiballZ_ntc_file_copy.py
<99.99.99.99> EXEC /bin/sh -c 'chmod u+x /home/guy/.ansible/tmp/ansible-local-18577FekORD/ansible-tmp-1552586644.8-88084817997960/ /home/guy/.ansible/tmp/ansible-local-18577FekORD/ansible-tmp-1552586644.8-88084817997960/AnsiballZ_ntc_file_copy.py && sleep 0'
<99.99.99.99> EXEC /bin/sh -c '/usr/bin/python /home/guy/.ansible/tmp/ansible-local-18577FekORD/ansible-tmp-1552586644.8-88084817997960/AnsiballZ_ntc_file_copy.py && sleep 0'
<99.99.99.99> EXEC /bin/sh -c 'rm -f -r /home/guy/.ansible/tmp/ansible-local-18577FekORD/ansible-tmp-1552586644.8-88084817997960/ > /dev/null 2>&1 && sleep 0'
changed: [teststack] => (item=1) => {
    "atomic": true,
    "changed": true,
    "file_system": "flash1:",
    "invocation": {
        "module_args": {
            "delay_factor": 1,
            "file_system": "flash1:",
            "global_delay_factor": 1,
            "host": "99.99.99.99",
            "local_file": "/home/guy/Ansible/images/c2960x-universalk9-mz.152-6.E2.bin",
            "ntc_conf_file": null,
            "ntc_host": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "platform": "cisco_ios_ssh",
            "port": null,
            "provider": null,
            "remote_file": null,
            "secret": null,
            "transport": null,
            "username": "guy"
        }
    },
    "item": "1",
    "local_file": "/home/guy/Ansible/images/c2960x-universalk9-mz.152-6.E2.bin",
    "remote_file": "c2960x-universalk9-mz.152-6.E2.bin",
    "transfer_status": "Sent"
}
<99.99.99.99> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/guy/.ansible/tmp/ansible-local-18577FekORD/ansible-tmp-1552587481.02-40589317800792 `" && echo ansible-tmp-1552587481.02-40589317800792="` echo /home/guy/.ansible/tmp/ansible-local-18577FekORD/ansible-tmp-1552587481.02-40589317800792 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/napalm_ansible/modules/ntc-ansible/library/ntc_file_copy.py
<99.99.99.99> PUT /home/guy/.ansible/tmp/ansible-local-18577FekORD/tmpAhoWM2 TO /home/guy/.ansible/tmp/ansible-local-18577FekORD/ansible-tmp-1552587481.02-40589317800792/AnsiballZ_ntc_file_copy.py
<99.99.99.99> EXEC /bin/sh -c 'chmod u+x /home/guy/.ansible/tmp/ansible-local-18577FekORD/ansible-tmp-1552587481.02-40589317800792/ /home/guy/.ansible/tmp/ansible-local-18577FekORD/ansible-tmp-1552587481.02-40589317800792/AnsiballZ_ntc_file_copy.py && sleep 0'
<99.99.99.99> EXEC /bin/sh -c '/usr/bin/python /home/guy/.ansible/tmp/ansible-local-18577FekORD/ansible-tmp-1552587481.02-40589317800792/AnsiballZ_ntc_file_copy.py && sleep 0'
<99.99.99.99> EXEC /bin/sh -c 'rm -f -r /home/guy/.ansible/tmp/ansible-local-18577FekORD/ansible-tmp-1552587481.02-40589317800792/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_ntc_file_copy_payload_JgsHCM/__main__.py", line 305, in main
    file_system=file_system)
  File "/usr/local/lib/python2.7/dist-packages/pyntc/devices/ios_device.py", line 225, in file_copy
    if not self.file_copy_remote_exists(src, dest, file_system):
  File "/usr/local/lib/python2.7/dist-packages/pyntc/devices/ios_device.py", line 232, in file_copy_remote_exists
    self._enable()
  File "/usr/local/lib/python2.7/dist-packages/pyntc/devices/ios_device.py", line 45, in _enable
    self.native.exit_config_mode()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 47, in exit_config_mode
    pattern=pattern)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 1360, in exit_config_mode
    if self.check_config_mode():
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 31, in check_config_mode
    pattern=pattern)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 1325, in check_config_mode
    self.write_channel(self.RETURN)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 360, in write_channel
    self._write_channel(out_data)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 331, in _write_channel
    self.remote_conn.sendall(write_bytes(out_data, encoding=self.encoding))
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 846, in sendall
    sent = self.send(s)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 1180, in _send
    raise socket.error("Socket is closed")
failed: [teststack] (item=2) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "delay_factor": 1,
            "file_system": "flash2:",
            "global_delay_factor": 1,
            "host": "99.99.99.99",
            "local_file": "/home/guy/Ansible/images/c2960x-universalk9-mz.152-6.E2.bin",
            "ntc_conf_file": null,
            "ntc_host": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "platform": "cisco_ios_ssh",
            "port": null,
            "provider": null,
            "remote_file": null,
            "secret": null,
            "transport": null,
            "username": "guy"
        }
    },
    "item": "2",
    "msg": "Socket is closed"
}

**Comment by gittyguy** [comment]
Forgot to mention that the file is correctly copied on the second flash drive tough.

**Comment by gittyguy** [comment]
Can I have some feedback please ?

**Comment by jmcgill298** [comment]
@gittyguy it looks like netmiko is trying to send data to the switch, but the underlying paramiko connection has closed the socket. Do you get the error if you increase the delay_factor and global_delay_factor?

**Comment by gittyguy** [comment]
Hello, 
ok sure no problem, I've found the following info in the doc file but both are multiplication factors. 
It's unclear against what there are multiplying ? 
I believe 1 upload of 1 ios image takes around 7 minutes. With these numbers in mind what are possible values ? 
- delay_factor 
Multiplication factor for timing delays 
[Default: 1] 
- global_delay_factor 
Sets delay between operations. 
[Default: 1] 

Best regards, 
Guy 

Van: "Jacob McGill" <notifications@github.com> 
Aan: "networktocode/ntc-ansible" <ntc-ansible@noreply.github.com> 
Cc: "guy" <guy.vandewiel@telenet.be>, "Mention" <mention@noreply.github.com> 
Verzonden: Maandag 8 april 2019 09:26:00 
Onderwerp: Re: [networktocode/ntc-ansible] Socket Closed with ntc_file_copy (#242) 



[ https://github.com/gittyguy | @gittyguy ] it looks like netmiko is trying to send data to the switch, but the underlying paramiko connection has closed the socket. Do you get the error if you increase the delay_factor and global_delay_factor?

**Comment by jmcgill298** [comment]
The delay_factor will multiply the amount of time it waits to receive the expected device prompt before raising an exception.

https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html

**Comment by gittyguy** [comment]
I configured even a delay_factor of 12 but still getting 'Socket is closed'. 
Config :  
- name: "Copy boot image on all members in the stack"
    ntc_file_copy:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      platform: cisco_ios_ssh
      local_file: "/home/guy/Ansible/images/{{ new_image }}"
      file_system: "flash{{ item }}:"
      delay_factor: 12
#   Debug line to replace actual copying of file to gain time.
#   Comment from ntc_file_copy until remote_file. Uncomment line below.
#    debug: msg="New IOS image copied to flash{{ item }}"
    when: "(not(new_image in flash.stdout[0])) and (freespace|int > imagebytes|int)"
    loop: "{{ members }}"

Debug output : 
TASK [Copy boot image on all members in the stack] ************************************************
task path: /home/guy/Ansible/playbooks/access/iosupgrade/imagecopy.yml:2
<99.99.99.99> ESTABLISH LOCAL CONNECTION FOR USER: root
<99.99.99.99> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/guy/.ansible/tmp/ansible-local-18526lrwDyk/ansible-tmp-1556091592.91-38650503612668 `" && echo ansible-tmp-1556091592.91-38650503612668="` echo /home/guy/.ansible/tmp/ansible-local-18526lrwDyk/ansible-tmp-1556091592.91-38650503612668 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/napalm_ansible/modules/ntc-ansible/library/ntc_file_copy.py
<99.99.99.99> PUT /home/guy/.ansible/tmp/ansible-local-18526lrwDyk/tmpZCJrG7 TO /home/guy/.ansible/tmp/ansible-local-18526lrwDyk/ansible-tmp-1556091592.91-38650503612668/AnsiballZ_ntc_file_copy.py
<99.99.99.99> EXEC /bin/sh -c 'chmod u+x /home/guy/.ansible/tmp/ansible-local-18526lrwDyk/ansible-tmp-1556091592.91-38650503612668/ /home/guy/.ansible/tmp/ansible-local-18526lrwDyk/ansible-tmp-1556091592.91-38650503612668/AnsiballZ_ntc_file_copy.py && sleep 0'
<99.99.99.99> EXEC /bin/sh -c '/usr/bin/python /home/guy/.ansible/tmp/ansible-local-18526lrwDyk/ansible-tmp-1556091592.91-38650503612668/AnsiballZ_ntc_file_copy.py && sleep 0'
<99.99.99.99> EXEC /bin/sh -c 'rm -f -r /home/guy/.ansible/tmp/ansible-local-18526lrwDyk/ansible-tmp-1556091592.91-38650503612668/ > /dev/null 2>&1 && sleep 0'
changed: [teststack] => (item=1) => {
    "atomic": true, 
    "changed": true, 
    "file_system": "flash1:", 
    "invocation": {
        "module_args": {
            "delay_factor": 12, 
            "file_system": "flash1:", 
            "global_delay_factor": 1, 
            "host": "99.99.99.99", 
            "local_file": "/home/guy/Ansible/images/c2960x-universalk9-mz.152-6.E2.bin", 
            "ntc_conf_file": null, 
            "ntc_host": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "platform": "cisco_ios_ssh", 
            "port": null, 
            "provider": null, 
            "remote_file": null, 
            "secret": null, 
            "transport": null, 
            "username": "guy"
        }
    }, 
    "item": "1", 
    "local_file": "/home/guy/Ansible/images/c2960x-universalk9-mz.152-6.E2.bin", 
    "remote_file": "c2960x-universalk9-mz.152-6.E2.bin", 
    "transfer_status": "Sent"
}
<99.99.99.99> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/guy/.ansible/tmp/ansible-local-18526lrwDyk/ansible-tmp-1556092460.43-50250102010036 `" && echo ansible-tmp-1556092460.43-50250102010036="` echo /home/guy/.ansible/tmp/ansible-local-18526lrwDyk/ansible-tmp-1556092460.43-50250102010036 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/napalm_ansible/modules/ntc-ansible/library/ntc_file_copy.py
<99.99.99.99> PUT /home/guy/.ansible/tmp/ansible-local-18526lrwDyk/tmpUhlr5N TO /home/guy/.ansible/tmp/ansible-local-18526lrwDyk/ansible-tmp-1556092460.43-50250102010036/AnsiballZ_ntc_file_copy.py
<99.99.99.99> EXEC /bin/sh -c 'chmod u+x /home/guy/.ansible/tmp/ansible-local-18526lrwDyk/ansible-tmp-1556092460.43-50250102010036/ /home/guy/.ansible/tmp/ansible-local-18526lrwDyk/ansible-tmp-1556092460.43-50250102010036/AnsiballZ_ntc_file_copy.py && sleep 0'
<99.99.99.99> EXEC /bin/sh -c '/usr/bin/python /home/guy/.ansible/tmp/ansible-local-18526lrwDyk/ansible-tmp-1556092460.43-50250102010036/AnsiballZ_ntc_file_copy.py && sleep 0'
<99.99.99.99> EXEC /bin/sh -c 'rm -f -r /home/guy/.ansible/tmp/ansible-local-18526lrwDyk/ansible-tmp-1556092460.43-50250102010036/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_ntc_file_copy_payload_xgUWSb/__main__.py", line 305, in main
    file_system=file_system)
  File "/usr/local/lib/python2.7/dist-packages/pyntc/devices/ios_device.py", line 225, in file_copy
    if not self.file_copy_remote_exists(src, dest, file_system):
  File "/usr/local/lib/python2.7/dist-packages/pyntc/devices/ios_device.py", line 232, in file_copy_remote_exists
    self._enable()
  File "/usr/local/lib/python2.7/dist-packages/pyntc/devices/ios_device.py", line 45, in _enable
    self.native.exit_config_mode()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 47, in exit_config_mode
    pattern=pattern)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 1360, in exit_config_mode
    if self.check_config_mode():
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 31, in check_config_mode
    pattern=pattern)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 1325, in check_config_mode
    self.write_channel(self.RETURN)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 360, in write_channel
    self._write_channel(out_data)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 331, in _write_channel
    self.remote_conn.sendall(write_bytes(out_data, encoding=self.encoding))
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 846, in sendall
    sent = self.send(s)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 1180, in _send
    raise socket.error("Socket is closed")
failed: [teststack] (item=2) => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "delay_factor": 12, 
            "file_system": "flash2:", 
            "global_delay_factor": 1, 
            "host": "99.99.99.99", 
            "local_file": "/home/guy/Ansible/images/c2960x-universalk9-mz.152-6.E2.bin", 
            "ntc_conf_file": null, 
            "ntc_host": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "platform": "cisco_ios_ssh", 
            "port": null, 
            "provider": null, 
            "remote_file": null, 
            "secret": null, 
            "transport": null, 
            "username": "guy"
        }
    }, 
    "item": "2", 
    "msg": "Socket is closed"
}

**Comment by gittyguy** [comment]
I timed the transfer of the IOS image to 1 flash drive, it takes around 14 minutes.
In the playbook the delay_factor was configured to 30 which corresponds to 2000 seconds (33 minutes).
I still get the message 'Socket is closed'.

**Comment by gittyguy** [comment]
Do you see something in the debug information or something wrong in my configuration ?

**Comment by mschedrin** [comment]
I'm facing the same issue. I seem to have found the root case of it. On the switch I troubleshoot default ssh session timeout is 20 minutes(`show line vty 0`), software transfer takes longer time. ntc_file_copy ssh session times out while it waits for the file gets transferred via scp. This parameter is configurable:
```
line vty 0 15
  session-timout 60
```
However there seems to be a bug in the software as it does not impact actual session timeout that stays 20 regardless of configuration. I've not found a proper workaround yet, but ignoring error and verifying file integrity in next task might be a solution.

**Comment by ericdost** [comment]
I am also getting the socket is closed error.  I did bump up session-timeout and I verified the VTY is still active as the file finishes transferring, but I still get the error.  My transfer takes forever (45+ mins), but it completes successfully.  It just errors improperly.

**Comment by ericdost** [comment]
To follow up: You need to increase the exec-timeout in order to fix this.  I increased both session and exec timeout and that fixed the issue:
```line vty 0 15
  session-timeout 60
  exec-timeout 60
```

**Comment by jeffkala** [comment]
closing. Please retest now that #268 is deployed and 1.0.0 of this collection is in ansible-galaxy now.
