### ISSUE TITLE
Module failure when trying to use 'ntc_show_command'

### ISSUE THREAD

**Issue by dkischkower** [networktocode/ntc-ansible#244]
Hi all,

I am having difficulty executing a basic 'ntc_show_command' function call.  Any help would be greatly appreciated!

Here is the error I am receiving:
dkischkower@ww-net-ansible:~/ansible$ ansible-playbook -i inventory test.yml -vvv
ansible-playbook 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dkischkower/projects', u'/etc/ansible/library']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /home/dkischkower/ansible/inventory as it did not pass it's verify_file() method
script declined parsing /home/dkischkower/ansible/inventory as it did not pass it's verify_file() method
auto declined parsing /home/dkischkower/ansible/inventory as it did not pass it's verify_file() method
Parsed /home/dkischkower/ansible/inventory inventory source with ini plugin

PLAYBOOK: test.yml ***************************************************************************************************************************************
1 plays in test.yml
Please enter the password: 

PLAY [Backup configuration] ******************************************************************************************************************************
META: ran handlers

TASK [BACKUP CONFIGS FOR ALL DEVICES] ********************************************************************************************************************
task path: /home/dkischkower/ansible/test.yml:24
<10.255.202.1> ESTABLISH LOCAL CONNECTION FOR USER: dkischkower
<10.255.202.1> EXEC /bin/sh -c 'echo ~dkischkower && sleep 0'
<10.255.202.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/dkischkower/.ansible/tmp/ansible-tmp-1564769005.01-227243417279617 `" && echo ansible-tmp-1564769005.01-227243417279617="` echo /home/dkischkower/.ansible/tmp/ansible-tmp-1564769005.01-227243417279617 `" ) && sleep 0'
<10.255.202.1> Attempting python interpreter discovery
<10.255.202.1> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<10.255.202.1> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
<10.255.202.1> Python interpreter discovery fallback (unsupported Linux distribution: debian)
Using module file /etc/ansible/library/ntc-ansible/library/ntc_show_command.py
<10.255.202.1> PUT /home/dkischkower/.ansible/tmp/ansible-local-1907kd4jIK/tmp4sIiyA TO /home/dkischkower/.ansible/tmp/ansible-tmp-1564769005.01-227243417279617/AnsiballZ_ntc_show_command.py
<10.255.202.1> EXEC /bin/sh -c 'chmod u+x /home/dkischkower/.ansible/tmp/ansible-tmp-1564769005.01-227243417279617/ /home/dkischkower/.ansible/tmp/ansible-tmp-1564769005.01-227243417279617/AnsiballZ_ntc_show_command.py && sleep 0'
<10.255.202.1> EXEC /bin/sh -c '/usr/bin/python /home/dkischkower/.ansible/tmp/ansible-tmp-1564769005.01-227243417279617/AnsiballZ_ntc_show_command.py && sleep 0'
<10.255.202.1> EXEC /bin/sh -c 'rm -f -r /home/dkischkower/.ansible/tmp/ansible-tmp-1564769005.01-227243417279617/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/dkischkower/.ansible/tmp/ansible-tmp-1564769005.01-227243417279617/AnsiballZ_ntc_show_command.py", line 114, in <module>
    _ansiballz_main()
  File "/home/dkischkower/.ansible/tmp/ansible-tmp-1564769005.01-227243417279617/AnsiballZ_ntc_show_command.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/dkischkower/.ansible/tmp/ansible-tmp-1564769005.01-227243417279617/AnsiballZ_ntc_show_command.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_ntc_show_command_payload_V6AXpM/__main__.py", line 511, in <module>
  File "/tmp/ansible_ntc_show_command_payload_V6AXpM/__main__.py", line 359, in main
NameError: global name 'return_values' is not defined

 [WARNING]: Platform linux on host 10.255.202.1 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python
interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information.

fatal: [10.255.202.1]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/dkischkower/.ansible/tmp/ansible-tmp-1564769005.01-227243417279617/AnsiballZ_ntc_show_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/dkischkower/.ansible/tmp/ansible-tmp-1564769005.01-227243417279617/AnsiballZ_ntc_show_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/dkischkower/.ansible/tmp/ansible-tmp-1564769005.01-227243417279617/AnsiballZ_ntc_show_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_ntc_show_command_payload_V6AXpM/__main__.py\", line 511, in <module>\n  File \"/tmp/ansible_ntc_show_command_payload_V6AXpM/__main__.py\", line 359, in main\nNameError: global name 'return_values' is not defined\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

PLAY RECAP ***********************************************************************************************************************************************
10.255.202.1               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Inventory File:
[all:vars]
ansible_user=dkischkower

[cisco]
10.255.202.20

[cisco:vars]
ansible_network_os=ios
ntc_vendor=cisco

[juniper]
10.255.202.1

[juniper:vars]
ansible_network_os=junos
ntc_vendor=juniper

Ansible File:
---

  - name: Backup configuration
    hosts: juniper
    connection: local
    gather_facts: no

    vars_prompt:
      - name: ansible_ssh_pass
        prompt: "Please enter the password"

    vars:
      backup_command:
        eos: show run
        ios: show run
        nxos: show run
        junos: show configuration    
      connection_details:
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        host: "{{ inventory_hostname }}"

    tasks:
      - name: BACKUP CONFIGS FOR ALL DEVICES    
        ntc_show_command:
          provider: "{{ connection_details }}"
          command: "{{ backup_command[ansible_network_os] }}"
          local_file: "./backups/{{ inventory_hostname }}.cfg"
          platform: "{{ ntc_vendor }}_{{ ansible_network_os }}"

**Comment by jmcgill298** [comment]
@dkischkower thanks for reporting this. Ansible2.8 removed a function that we are using to keep passwords in the `provider` argument from displaying in the stdout of playbook execution. I have a solution from other modules that should be able to implement here also. Until we are able to get that merged, you should be able to use Ansible2.7 or lower.

**Comment by jmcgill298** [comment]
#245
