### ISSUE TITLE
ntc_show__command cant find netmiko

### ISSUE THREAD

**Issue by wallacj** [networktocode/ntc-ansible#257]
I get this error when trying to run the playbook below, any help would be greatly appreciated.

fatal: [10.10.1.9 zoom-core]: FAILED! => {"changed": false, "msg": "This module requires netmiko."}

---

- name: GET STRUCTURED DATA BACK FROM CLI DEVICES
  hosts: all
  connection: local
  #gather_facts: false
  
  tasks:

    - name: GET VLANS IN REAL TIME
      ntc_show_command:
        connection: netmiko_ssh
        platform: 'hp_procurve'
        command: 'show vlans'
        template_dir: "/usr/share/my_modules/ntc-ansible/ntc-templates/templates" # Specifies where to search templates
        host: "{{ inventory_hostname }}"
        username: 'manager'
        password: 'somepassword'
      register: result

    - debug:  var=result

___________________________________________
ansible --version
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/my_modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]

**Comment by jmcgill298** [comment]
The python environment that Ansible is using to execute the module does not have netmiko installed. You either need to install netmiko or set the [ansible_python_interpreter](https://docs.ansible.com/ansible/latest/reference_appendices/interpreter_discovery.html) variable appropriately within Ansible.

**Comment by jmcgill298** [comment]
@wallacj were you able to get this working?

**Comment by jarkowski** [comment]
I am having the same problem: "This module requires netmiko"

Netmiko is installed.

To rule out any problems with my setup, I installed a fresh Ubuntu 18.04 with only the minimum required for ntc-ansible. I can not figure out why it would not find the netmiko module.


```
ansible --version
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible-modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]

pip show netmiko
Name: netmiko
Version: 3.0.0
Summary: Multi-vendor library to simplify Paramiko SSH connections to network devices
Home-page: https://github.com/ktbyers/netmiko
Author: Kirk Byers
Author-email: ktbyers@twb-tech.com
License: MIT
Location: /home/anwender/.local/lib/python2.7/site-packages
Requires: pyserial, paramiko, scp, setuptools, textfsm

python -V
Python 2.7.17

```

I did not make any changes to the default setup besides creating  `/usr/share/ansible-modules/` and setting

```
ansible.cfg
[defaults]
library        = /usr/share/ansible-modules/
```

**Comment by FragmentedPacket** [comment]
@jarkowski What commands did you use to install? It appears there is a discrepancy between where Ansible gets executed `/usr/bin/ansible` and where Netmiko is installed `home/anwender/.local/lib//python2.7/site-packages`. If you launch Python and try and import `netmiko` does that work? And as @jmcgill298 suggested above, you will probably have to set the Python interpreter variable.

**Comment by jarkowski** [comment]
@FragmentedPacket  I also thought that the paths' mismatch, but in the end, it was solved by using an older netmiko version.

We could get it working by downgrading the netmiko version:

`sudo -H pip3 install --upgrade --force-reinstall netmiko==2.4.2`
`sudo -H pip install --upgrade --force-reinstall netmiko==2.4.2`

Not sure if this is the correct way, but it solved it for me. Changing the interpreter just changed the error message, another module was then missing.

**Comment by krisvoegele** [comment]
I had this same issue and a downgrade fixed the issue (uninstall the re-install). Per ktbyers:
`ktbyers commented on Jan 27
Netmiko no longer supports PY27.

For PY27, you would need to pip install netmiko==2.4.2`
