### ISSUE TITLE
Move into Ansible Collection

### ISSUE THREAD

**Issue by FragmentedPacket** [networktocode/ntc-ansible#259]
Make necessary changes to make this an Ansible Collection.

Some internal discussions to be had, but wanted an issue open to signify the intent to move to an Ansible collection.

**Comment by jvanderaa** [comment]
This definitely should get done. Not sure how we go about it. Now that we have the networktocode setup on Galaxy that we should be able to get going on that.

**Comment by jeffkala** [comment]
closing. Please retest now that #268 is deployed and 1.0.0 of this collection is in ansible-galaxy now.
