### ISSUE TITLE
Matching list items spanning multiple columns and rows

### ISSUE THREAD

**Issue by jtdub** [networktocode/ntc-ansible#26]
Does anybody know how one would go about matching FSM list items that can, but may not span multiple columns and rows?

For example, each port-channel should have a list of physical interfaces:

```
                 Flags
------------------------ ---------------------------- -------------------------
  a - LACP Active          p - LACP Passive           * - static fallback
  F - Fallback enabled     f - Fallback configured    ^ - individual fallback
  U - In Use               D - Down
  + - In-Sync              - - Out-of-Sync            i - incompatible with agg
  P - bundled in Po        s - suspended              G - Aggregable
  I - Individual           S - ShortTimeout           w - wait for agg

Number of channels in use: 26
Number of aggregators:26

Port-Channel Protocol  Ports
------------ --------- --------------------------------------------------------
Po1(U)       LACP(a)    Et3/36/1(PG+)
Po25(D)      LACP(a)    Et3/12/1(G-)
Po101(U)     LACP(a)    Et3/1/1(PSG+) Et3/1/2(PSG+) Et3/1/3(PSG+) Et3/1/4(PSG+)
                        Et3/3/1(PSG+) Et3/3/2(PSG+) Et3/3/3(PSG+) Et3/3/4(PSG+)
Po102(U)     LACP(a)    Et3/2/1(PSG+) Et3/2/2(PSG+) Et3/2/3(PSG+) Et3/2/4(PSG+)
```

**Comment by jedelman8** [comment]
This is an interesting one.  This is one of the reasons, it could make sense to port some of the functions in the module to an external helper lib.

I've tested this template (notice the "List" parameter for INTFS):
```
Value VLAN_ID (\d+)
Value NAME (\w+)
Value STATUS (\w+)
Value List INTFS ((\w+.\w+,?\s?)*)

Start
  ^\d+ -> Continue.Record
  ^${VLAN_ID}\s+${NAME}\s+${STATUS}\s+${INTFS}
  ^\s+${INTFS}


```

With this data:

```

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
                                                Eth1/9, Eth1/10, Eth1/11
                                                Eth1/12, Eth1/13, Eth1/14
                                                Eth1/15, Eth1/16, Eth1/17
                                                Eth1/18, Eth1/19, Eth1/20
                                                Eth1/21, Eth1/22, Eth1/23
                                                Eth1/24, Eth1/25, Eth1/26
                                                Eth1/27, Eth1/28, Eth1/29
                                                Eth1/30, Eth1/31, Eth1/32
                                                Eth1/33, Eth1/34, Eth1/35
                                                Eth1/36, Eth1/37, Eth1/38
                                                Eth1/39, Eth1/40, Eth1/41
                                                Eth1/42, Eth1/43, Eth1/44
                                                Eth1/45, Eth1/46, Eth1/47
                                                Eth1/48, Eth1/51, Eth1/52
2    VLAN0002                         active    Po100, Eth1/49, Eth1/50, Eth1/52
3    VLAN0003                         active    Po100, Eth1/49, Eth1/50
4    VLAN0004                         active    Po100, Eth1/49, Eth1/50
5    VLAN0005                         active    Po100, Eth1/49, Eth1/50
6    VLAN0006                         active    Po100, Eth1/49, Eth1/50
7    VLAN0007                         active    Po100, Eth1/49, Eth1/50
8    VLAN0008                         active    Po100, Eth1/49, Eth1/50
9    VLAN0009                         active
10   test_segment                     active    Po100, Eth1/49, Eth1/50
11   VLAN0011                         active    Po100, Eth1/49, Eth1/50
12   VLAN0012                         active    Po100, Eth1/49, Eth1/50
13   VLAN0013                         active    Po100, Eth1/49, Eth1/50
14   VLAN0014                         active    Po100, Eth1/49, Eth1/50
15   VLAN0015                         active    Po100, Eth1/49, Eth1/50
16   VLAN0016                         active    Po100, Eth1/49, Eth1/50
17   VLAN0017                         active    Po100, Eth1/49, Eth1/50
18   VLAN0018                         active    Po100, Eth1/49, Eth1/50
19   VLAN0019                         active    Po100, Eth1/49, Eth1/50
99   native                           active    

```

And just the native testfsm output is this:

```
cisco@ntc:~/projects/legacy/textfsm/textfsm-0.2.1$ python textfsm.py show_vlan.templ show_vlan.txt
FSM Template:
Value VLAN_ID (\d+)
Value NAME (\w+)
Value STATUS (\w+)
Value List INTFS ((\w+.\w+,?\s?)*)

Start
  ^\d+ -> Continue.Record
  ^${VLAN_ID}\s+${NAME}\s+${STATUS}\s+${INTFS}
  ^\s+${INTFS}


FSM Table:
['VLAN_ID', 'NAME', 'STATUS', 'INTFS']
['1', 'default', 'active', ['Eth1/1, Eth1/2, Eth1/3, Eth1/4', 'Eth1/5, Eth1/6, Eth1/7, Eth1/8', 'Eth1/9, Eth1/10, Eth1/11', 'Eth1/12, Eth1/13, Eth1/14', 'Eth1/15, Eth1/16, Eth1/17', 'Eth1/18, Eth1/19, Eth1/20', 'Eth1/21, Eth1/22, Eth1/23', 'Eth1/24, Eth1/25, Eth1/26', 'Eth1/27, Eth1/28, Eth1/29', 'Eth1/30, Eth1/31, Eth1/32', 'Eth1/33, Eth1/34, Eth1/35', 'Eth1/36, Eth1/37, Eth1/38', 'Eth1/39, Eth1/40, Eth1/41', 'Eth1/42, Eth1/43, Eth1/44', 'Eth1/45, Eth1/46, Eth1/47', 'Eth1/48, Eth1/51, Eth1/52']]
['2', 'VLAN0002', 'active', ['Po100, Eth1/49, Eth1/50, Eth1/52']]
['3', 'VLAN0003', 'active', ['Po100, Eth1/49, Eth1/50']]
['4', 'VLAN0004', 'active', ['Po100, Eth1/49, Eth1/50']]
['5', 'VLAN0005', 'active', ['Po100, Eth1/49, Eth1/50']]
['6', 'VLAN0006', 'active', ['Po100, Eth1/49, Eth1/50']]
['7', 'VLAN0007', 'active', ['Po100, Eth1/49, Eth1/50']]
['8', 'VLAN0008', 'active', ['Po100, Eth1/49, Eth1/50']]
['10', 'test_segment', 'active', ['Po100, Eth1/49, Eth1/50']]
['11', 'VLAN0011', 'active', ['Po100, Eth1/49, Eth1/50']]
['12', 'VLAN0012', 'active', ['Po100, Eth1/49, Eth1/50']]
['13', 'VLAN0013', 'active', ['Po100, Eth1/49, Eth1/50']]
['14', 'VLAN0014', 'active', ['Po100, Eth1/49, Eth1/50']]
['15', 'VLAN0015', 'active', ['Po100, Eth1/49, Eth1/50']]
['16', 'VLAN0016', 'active', ['Po100, Eth1/49, Eth1/50']]
['17', 'VLAN0017', 'active', ['Po100, Eth1/49, Eth1/50']]
['18', 'VLAN0018', 'active', ['Po100, Eth1/49, Eth1/50']]
['19', 'VLAN0019', 'active', ['Po100, Eth1/49, Eth1/50']]
['99', 'native', 'active', ['']]
cisco@ntc:~/projects/legacy/textfsm/textfsm-0.2.1$ 
```

This is OK, but not great because it's actually a list of string elements.  For reporting, this would probably work, but if you wanted to loop through or record each element individually, we would need to massage this data in a helper function.  This also means, we would need to touch the Python code in ntc_show_command to say if command is X, call this helper, else call the single helper that is in the module.


More detail on "list" here: https://code.google.com/p/textfsm/wiki/TextFSMCodeLab

Any thoughts?

**Comment by ktbyers** [comment]
@jedelman8 I haven't thought about the issue of the list of strings and how to manage multiple helper functions so I might comment on that part of it later.

I do think it would be helpful to allow 'clitable_to_dict' and other helper functions that you create to be separately importable. This would be helpful to me as I would be interested in using the Textfsm templates and helper functions straight from a Python program (not wrapped in Ansible). So this would allow me to avoid duplicating code.

The simple way to do this is to just use the __name__ technique in the Ansible 'ntc_show_command'. Ansible modules seem to generally not do this, but when I have tested it, I have never seen a problem (with __name__ == "__main__"). This will cause problems, however, if you create additional Ansible modules that you want to use the same helper functions (as you might have to duplicate code).

The other option is to create some sort of a module that you install somewhere on the Python Path separately.

**Comment by jtdub** [comment]
It would definitely be helpful to have a helper library, or have the functionality native to textfsm.

It's fairly easy to do natively in python, as seen here:

https://github.com/jtdub/netcli_to_dict/tree/master/cisco_nxos_show_port-channel_summary

I'll take a closer look at the underlying code and see if I can create a helper over the next week, or so, as time allows.

**Comment by jedelman8** [comment]
Thanks for the comments guys.  

@ktbyers I've already used textfsm in other native python programs too and kept this type of intelligence local to the programs.  Definitely worth de-coupling the helper module(s) from the Ansible module, just want to keep things simple for EVERYONE :).  But no doubt, that's where it will end up going.

@jtdub No doubt it's possible.  I may explore this for the port-channel command you are showing next week and keep the helper in the Ansible module for now.

**Comment by GGabriele** [comment]
Today I tried to solve this trying to find a general solution converting the multiline field into a string. I've done few changes to the python code and tested it with two type of output:

show banner motd (Cisco NX-OS/IOS):

    User Access Verification
    DISCONNECT FROM DEVICE IMMEDIATELY.
    IF YOU CONTINUE, YOU WILL BE PROSECUTED TO THE FULLEST
    EXTENT OF THE LAW!!!

Obtaining:

    PLAY [GET STRUCTURED DATA BACK FROM CLI DEVICES] ****************************** 

    TASK: [TEST] ****************************************************************** 
    ok: [n9k1] => {"changed": false, "response": [{"banner": "User Access Verification DISCONNECT FROM DEVICE IMMEDIATELY. IF YOU CONTINUE, YOU WILL BE PROSECUTED TO THE FULLEST EXTENT OF THE LAW!!!"}]}

    TASK: [debug var=test.response] ********************************************** 
    ok: [n9k1] => {
        "var": {
            "test.response": [
                {
                    "banner": "User Access Verification DISCONNECT FROM DEVICE IMMEDIATELY. IF YOU CONTINUE, YOU WILL BE PROSECUTED TO THE FULLEST EXTENT OF THE LAW!!!"
                 }
             ]
         }
    }

show mac address-table (Arista EOS):

              Mac Address Table
    ------------------------------------------------------------------

    Vlan    Mac Address       Type        Ports      Moves   Last Move
    ----    -----------       ----        -----      -----   ---------
       1    000a.000a.000a    STATIC      Et1
    3909    001c.822f.6a80    DYNAMIC     Po1        1       0:07:08 ago
    3912    001c.822b.033e    DYNAMIC     Et11       1       9 days, 15:57:23 ago
    3992    001c.8220.1319    DYNAMIC     Po1
    3992    001c.8221.07b9    DYNAMIC     Po6        1       4 days, 15:13:15 ago

    Total Mac Addresses for this criterion: 5

              Multicast Mac Address Table
    ------------------------------------------------------------------

    Vlan    Mac Address       Type        Ports
    ----    -----------       ----        -----
       4    0112.3057.8423    STATIC      Et1 Et2 Po1 Po2 Po3 Po4 Po5 Po6 Po7 Po8
				      Et19 Et20

    Total Mac Addresses for this criterion: 1

Obtaining:

    TASK: [debug var=test.response] ********************************************** 
    ok: [n9k1] => {
        "var": {
            "test.response": [
                {
                    "last_move": "", 
                    "mac": "000a.000a.000a", 
                    "moves": "", 
                    "ports": "Et1", 
                    "type": "STATIC", 
                    "vlan": "1"
                }, 
                {
                    "last_move": "0:07:08 ago", 
                    "mac": "001c.822f.6a80", 
                    "moves": "1", 
                    "ports": "Po1", 
                    "type": "DYNAMIC", 
                    "vlan": "3909"
                }, 
                {
                    "last_move": "9 days, 15:57:23 ago", 
                    "mac": "001c.822b.033e", 
                    "moves": "1", 
                    "ports": "Et11", 
                    "type": "DYNAMIC", 
                    "vlan": "3912"
                }, 
                {
                    "last_move": "", 
                    "mac": "001c.8220.1319", 
                    "moves": "", 
                    "ports": "Po1", 
                    "type": "DYNAMIC", 
                    "vlan": "3992"
                }, 
                {
                    "last_move": "4 days, 15:13:15 ago", 
                    "mac": "001c.8221.07b9", 
                    "moves": "1", 
                    "ports": "Po6", 
                    "type": "DYNAMIC", 
                    "vlan": "3992"
                }, 
                {
                    "last_move": "", 
                    "mac": "0112.3057.8423", 
                    "moves": "", 
                    "ports": "Et1 Et2 Po1 Po2 Po3 Po4 Po5 Po6 Po7 Po8 Et19 Et20", 
                    "type": "STATIC", 
                    "vlan": "4"
                }
             ]
        }
    }

Any thoughts about this?

**Comment by jtdub** [comment]
Having the items in a string means that you have to go through extra gyrations to extract individual items to do something with them. Ideally, the items would be in a list.  I had some thoughts about this the other day, but I haven't actually written out the helper, yet.

**Comment by jedelman8** [comment]
I think there is room for more than one helper here.  The one for motd is
different as it's really not structured at all.  Although still knowing
where the line breaks are would be nice.

The one for portchannel ( I think) and others like it, are good examples of
multi-line semi-structured data, where we'll have a list (as it is today),
but each element is actually multiple elements, so we need to parse
manually.....net net, we can have more than 1 helper.  In December, I'd
like to spend more time on building out a mini-lib that could do this for
us.

**Comment by GGabriele** [comment]
You're both right.
I tried to fix my previous proposal and now the output are:

    TASK: [debug var=test.response] ********************************************** 
    ok: [arista1] => {
        "var": {
            "prova.response": [
                {
                    "last_move": "", 
                    "mac": "000a.000a.000a", 
                    "moves": "", 
                    "ports": [
                        "Et1"
                        ], 
                    "type": "STATIC", 
                    "vlan": "1"
                }, 
                {
                    "last_move": "0:07:08 ago", 
                    "mac": "001c.822f.6a80", 
                    "moves": "1", 
                    "ports": [
                        "Po1"
                    ], 
                    "type": "DYNAMIC", 
                    "vlan": "3909"
                }, 
                {
                    "last_move": "9 days, 15:57:23 ago", 
                    "mac": "001c.822b.033e", 
                    "moves": "1", 
                    "ports": [
                        "Et11"
                    ], 
                    "type": "DYNAMIC", 
                    "vlan": "3912"
                }, 
                {
                    "last_move": "", 
                    "mac": "001c.8220.1319", 
                    "moves": "", 
                    "ports": [
                        "Po1"
                    ], 
                    "type": "DYNAMIC", 
                    "vlan": "3992"
                }, 
                {
                    "last_move": "4 days, 15:13:15 ago", 
                    "mac": "001c.8221.07b9", 
                    "moves": "1", 
                    "ports": [
                        "Po6"
                    ], 
                    "type": "DYNAMIC", 
                    "vlan": "3992"
                }, 
                {
                    "last_move": "", 
                    "mac": "0112.3057.8423", 
                    "moves": "", 
                    "ports": [
                        "Et1", 
                        "Et2", 
                        "Po1", 
                        "Po2", 
                        "Po3", 
                        "Po4", 
                        "Po5", 
                        "Po6", 
                        "Po7", 
                        "Po8", 
                        "Et19", 
                        "Et20"
                    ], 
                    "type": "STATIC", 
                    "vlan": "4"
                }
            ]
        }
   }

and..

    PLAY [GET STRUCTURED DATA BACK FROM CLI DEVICES] ****************************** 

    TASK: [TEST] ****************************************************************** 
    ok: [n9k1] => {"changed": false, "response": [{"banner": "User Access Verification DISCONNECT FROM DEVICE IMMEDIATELY. IF YOU CONTINUE, YOU WILL BE PROSECUTED TO THE FULLEST EXTENT OF THE LAW!!!"}]}

     TASK: [debug var=test.response] ********************************************** 
     ok: [n9k1] => {
        "var": {
            "test.response": [
                {
                    "banner": "User Access Verification DISCONNECT FROM DEVICE IMMEDIATELY. IF YOU CONTINUE, YOU WILL BE PROSECUTED TO THE FULLEST EXTENT OF THE LAW!!!"
                 }
             ]
         }
    }

What I did is mapping multiline_commands with multiline_fields like this:

        semi_multiline_commands = {
         'show mac address-table': 'ports'
        }

        multiline_commands = {
        'show banner motd': 'banner',
        }

and then I modified the code like this:

    structured_data = clitable_to_dict(cli_table)
        if command in semi_multiline_commands:
            for element in structured_data:
                key = semi_multiline_commands[command]
                element[key] = " ".join(element[key]).split(' ')
        elif command in multiline_commands:
            for element in structured_data:
                key = multiline_commands[command]
                element[key] = " ".join(element[key])

        results = {}
        results['response'] = structured_data

**Comment by itdependsnetworks** [comment]
@jtdub Just doing some clean up, I think I have updated this one that should satisfy all. Let me know if this could be closed.

Template:
https://github.com/networktocode/ntc-templates/blob/master/templates/cisco_nxos_show_port-channel_summary.template

```
Value Required,Filldown BUNDLE_IFACE (Po\d+)
Value Filldown BUNDLE_STATUS (\(\w+\))
Value Filldown BUNDLE_PROTO (\w+)
Value Filldown BUNDLE_PROTO_STATE (\(\w+\))
Value List PHYS_IFACE (Et.+?)
Value List PHYS_IFACE_STATUS (\(.+?\))


Start
  ^\s+Flag -> CASE1
  ^Flags: -> CASE2


CASE1
  ^.*------------ -> CASE1_RTE

CASE1_RTE
  ^Po -> Continue.Record
  ^${BUNDLE_IFACE}${BUNDLE_STATUS}\s+${BUNDLE_PROTO}${BUNDLE_PROTO_STATE}\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^Po\d+\(\w+\)\s+\w+\(\w+\)\s+Et.+?\(.+?\)\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^Po\d+\(\w+\)\s+\w+\(\w+\)\s+Et.+?\(.+?\)\s+Et.+?\(.+?\)\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^Po\d+\(\w+\)\s+\w+\(\w+\)\s+Et.+?\(.+?\)\s+Et.+?\(.+?\)\s+Et.+?\(.+?\)\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^Po\d+\(\w+\)\s+\w+\(\w+\)\s+Et.+?\(.+?\)\s+Et.+?\(.+?\)\s+Et.+?\(.+?\)\s+Et.+?\(.+?\)\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^Po\d+\(\w+\)\s+\w+\(\w+\)\s+Et.+?\(.+?\)\s+Et.+?\(.+?\)\s+Et.+?\(.+?\)\s+Et.+?\(.+?\)\s+Et.+?\(.+?\)\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^\s{24}${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^\s{24}Et.+?\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^\s{24}Et.+?\s+Et.+?\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^\s{24}Et.+?\s+Et.+?\s+Et.+?\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^\s{24}Et.+?\s+Et.+?\s+Et.+?\s+Et.+?\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue


CASE2
  ^Group\s+Port -> CASE2_RTE

CASE2_RTE
  ^------------ -> Next
  ^\d+ -> Continue.Record
  ^\d+\s+${BUNDLE_IFACE}${BUNDLE_STATUS}\s+\w+\s+${BUNDLE_PROTO}\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^\d+\s+Po\d+\(\w+\)\s+\w+\s+\w+\s+Et.+?\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^\d+\s+Po\d+\(\w+\)\s+\w+\s+\w+\s+Et.+?\s+Et.+?\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^\d+\s+Po\d+\(\w+\)\s+\w+\s+\w+\s+Et.+?\s+Et.+?\s+Et.+?\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^\s{37}${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^\s{37}Et.+?\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^\s{37}Et.+?\s+Et.+?\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
  ^\s{37}Et.+?\s+Et.+?\s+Et.+?\s+${PHYS_IFACE}${PHYS_IFACE_STATUS}(\s|$$) -> Continue
```

Output:
https://github.com/networktocode/ntc-templates/blob/master/tests/cisco_nxos/show_port-channel_summary/cisco_nxos_show_port-channel_summary.parsed

**Comment by itdependsnetworks** [comment]
@GGabriele I think we can close this one, unless @jtdub has anything further to add.
