### ISSUE TITLE
Can't figure out how to make it work with netmiko

### ISSUE THREAD

**Issue by Tiguespa** [networktocode/ntc-ansible#286]
### Environment
ansible [core 2.16.7]
python version = 3.11.2
Name: pyntc
Version: 2.0.0
Name: netmiko
Version: 4.3.0

both on my python3.11/site-packages

Firstly, I'm really a beginner, so feel free to provide information that seems already acquired to you.

I would like to use ntc-command to connect to various devices via SSH. It is said that pyntc relies on the same devices as netmiko. However, every time I try to execute a playbook, I get the same message:

"FAILED! => {"changed": false, "msg": "value of platform must be one of: arista_eos_eapi, cisco_aireos_ssh, cisco_asa_ssh, cisco_ios_ssh, cisco_nxos_nxapi, f5_tmos_icontrol, juniper_junos_netconf, got: fortinet"}"

having "from netmiko.fortinet import FortinetSSH
    "fortinet": FortinetSSH,"  in ssh_dispatcher

I have tested various things, but in the end, I never really manage to use, if I'm not mistaken, the ssh_dispatcher from netmiko as the source of devices. I can't find anything on the internet, I can't find anything anywhere, so I don't know what else to do other than to ask you.

So, what are the steps to be taken for ntc_config_command and ntc_show_command to be executed on my devices recognized by netmiko?

Thank you in advance, hoping to have been as clear as possible.

**Comment by jvanderaa** [comment]
What is the task looking like that you are using on this?
