### ISSUE TITLE
using changed in ntc_show_command

### ISSUE THREAD

**Issue by jtdub** [networktocode/ntc-ansible#64]
What are your thoughts on using the changed variable in ntc_show_command?

For example:
```
    results = {}
    results['response'] = structured_data

    if not results['response']:
        module.exit_json(changed=False)
    else:
        module.exit_json(changed=True, **results)
```

Some commands that I execute, don't have a matching output on all devices. I end up with output like:

```
ok: [router1] => {
    "output.response": []
}
ok: [router2] => {
    "output.response": "{{output.response}}"
}
ok: [router3] => {
    "output.response": [
        {
            "key": "value"
        }
    ]
}
```
In my use-case, I want to execute a task to build and push configurations to remediate devices, based on the results of the audit in Ansible. 

For example, I'd like to do something like:

```
- name: build remediation
  template:
      src=templates/some_config.j2
      dest=output/{{ inventory_hostname }}_some_config.conf
      when: output.changed
```
Thoughts?

**Comment by jedelman8** [comment]
Have you thought about using `when: output.response`  ?  It's *Pythonic* and will be true if a variable is in there.

**Comment by jedelman8** [comment]
Still want this open?

**Comment by jtdub** [comment]
Nope. I think we're good. :)
