### ISSUE TITLE
TextFSM State transition issue

### ISSUE THREAD

**Issue by GGabriele** [networktocode/ntc-ansible#75]
I'm going to write the template for the NX-OS "show interface brief" command but I'm having some issues with state transitions. (I'm rewriting it since my previous one had some bugs)

My raw file is this:

    --------------------------------------------------------------------------------
    Port   VRF          Status IP Address                              Speed    MTU
    --------------------------------------------------------------------------------
    mgmt0  --           up     10.1.100.20                             100      1500
    mgmt1  10           down   10.1.100.2                              1000     1500

    --------------------------------------------------------------------------------
    Ethernet      VLAN    Type Mode   Status  Reason                   Speed     Port
    Interface                                                                    Ch #
    --------------------------------------------------------------------------------
    Eth1/1        --      eth  routed down    Administratively down      auto(D) --
    Eth1/2        1       eth  access down    Administratively down      auto(D) --
    Eth1/3        1       eth  access down    XCVR not inserted          auto(D) --
    Eth1/4        2       eth  trunk  down    XCVR not inserted          auto(D) 10
    Eth1/5        2       eth  trunk  down    XCVR not inserted          auto(D) 10
    Eth1/8        1       eth  access down    XCVR not inserted          auto(D) --
    Eth1/9        1       eth  access down    XCVR not inserted          auto(D) -- 
    Eth1/10       --      eth  routed down    XCVR not inserted          auto(D) --
    Eth2/1        --      eth  routed down    Link not connected         auto(D) --
    Eth2/2        --      eth  routed down    Link not connected         auto(D) -- 
    Eth2/3        --      eth  routed down    Link not connected         auto(D) --
    Eth2/4        --      eth  routed down    Link not connected         auto(D) --
    Eth2/5        2       eth  trunk  down    XCVR not inserted          auto(D) 12
    Eth2/6        2       eth  trunk  down    XCVR not inserted          auto(D) 12 
    Eth2/7        1       eth  access down    XCVR not inserted          auto(D) --
    Eth2/8       1       eth  access down    Administratively down      auto(D) --

    --------------------------------------------------------------------------------
    Port-channel VLAN    Type Mode   Status  Reason                    Speed   Protocol
    Interface
    --------------------------------------------------------------------------------
    Po10         1       eth  trunk  down    No operational members      auto(D)  lacp
    Po11         1       eth  trunk  down    No operational members      auto(D)  lacp
    Po12         1       eth  trunk  down    No operational members      auto(D)  lacp

    --------------------------------------------------------------------------------
    Interface     Status     Description
    --------------------------------------------------------------------------------
    Lo10          up         --

    -------------------------------------------------------------------------------
    Interface Secondary VLAN(Type)                    Status Reason
    ------------------------------------------------------------------------------- 
    Vlan1     --                                      down   Administratively down
    Vlan5     --                                      down   VLAN/BD is down
    Vlan10    --                                      down   VLAN/BD is down
    Vlan20    --                                      down   VLAN/BD is down
    Vlan66    --                                      down   Administratively down
    Vlan77    --                                      down   Administratively down 
    Vlan146   --                                      down   Administratively down

So, I want to build a template with 5 states: MANAGEMENT, ETHERNET, PORTCH, LOOPBACK and VLAN. These are my Values

    Value INTERFACE (\S+)
    Value VRF (\S+)
    Value STATUS (up|down)
    Value IP (\d+\.\d+\.\d+\.\d+)
    Value SPEED (\S+)
    Value MTU (\d+)
    Value VLAN ([\d+--]+)
    Value TYPE (\S+)
    Value MODE (routed|access|trunk)
    Value REASON (\S+(\s\S+)*)
    Value PORTCH (\S+)
    Value DESCRIPTION (\S+(\s\S+)*)

And here it is my first 2 states:

    Start
      ^Port\s+VRF\s+Status\s+IP\s+Address\s+Speed\s+MTU -> Management

    Management
      ^${INTERFACE}\s+${VRF}\s+${STATUS}\s+${IP}\s+${SPEED}\s+${MTU} -> Record

If I test this, I obtain a well parsed table:

    FSM Table:
    ['INTERFACE', 'VRF', 'STATUS', 'IP', 'SPEED', 'MTU', 'VLAN', 'TYPE', 'MODE', 'REASON', 'PORTCH', 'DESCRIPTION']
    ['mgmt0', '--', 'up', '10.1.100.20', '100', '1500', '', '', '', '', '', '']
    ['mgmt1', '10', 'down', '10.1.100.2', '1000', '1500', '', '', '', '', '', '']

Then, I want to go back to the Start state as soon as the "-----" pattern is catched and so I update my states:

    Start
      ^Port\s+VRF\s+Status\s+IP\s+Address\s+Speed\s+MTU -> Management

    Management
      ^${INTERFACE}\s+${VRF}\s+${STATUS}\s+${IP}\s+${SPEED}\s+${MTU} -> Record
      ^.*----- -> Start

But when I test it again I catch absolutely nothing:

    FSM Table:
    ['INTERFACE', 'VRF', 'STATUS', 'IP', 'SPEED', 'MTU', 'VLAN', 'TYPE', 'MODE', 'REASON', 'PORTCH', 'DESCRIPTION']

I understood that, for some reason, TextFSM doesn't recognize the pattern to go back to Start.
The completed template should be this, but it catches nothing 

    Start
      ^Port\s+VRF\s+Status\s+IP\s+Address\s+Speed\s+MTU -> Management
      ^Ethernet\s+VLAN\s+Type\s+Mode\s+Status\s+Reason\s+Speed\s+Port -> Ethernet
      ^Interface\s+Status\s+Description -> Loopback
      ^Interface\s+Secondary\s+VLAN\(Type\)\s+Status\s+Reason -> VLAN

    Management
      ^${INTERFACE}\s+${VRF}\s+${STATUS}\s+${IP}\s+${SPEED}\s+${MTU} -> Record
      ^.*----- -> Start

    Ethernet
      ^${INTERFACE}\s+${VLAN}\s+${TYPE}\s+${MODE}\s+${STATUS}\s+${REASON}\s+${SPEED}\s+${PORTCH} -> Record
      ^.*----- -> Start

    Loopback
      ^${INTERFACE}\s+${STATUS}\s+${DESCRIPTION} -> Record
      ^.*----- -> Start

    VLAN
      ^${INTERFACE}\s+${TYPE}\s+${STATUS}\s+${REASON} -> Record

But eventually if I change state transitioning lines like follows, I catch only Management interfaces.

    Management
      ^${INTERFACE}\s+${VRF}\s+${STATUS}\s+${IP}\s+${SPEED}\s+${MTU} -> Record
      ^\n -> Start

    Ethernet
      ^${INTERFACE}\s+${VLAN}\s+${TYPE}\s+${MODE}\s+${STATUS}\s+${REASON}\s+${SPEED}\s+${PORTCH} -> Record
      ^\n -> Start

    Loopback
      ^${INTERFACE}\s+${STATUS}\s+${DESCRIPTION} -> Record
      ^\n -> Start

    VLAN
      ^${INTERFACE}\s+${TYPE}\s+${STATUS}\s+${REASON} -> Record

    FSM Table:
    ['INTERFACE', 'VRF', 'STATUS', 'IP', 'SPEED', 'MTU', 'VLAN', 'TYPE', 'MODE', 'REASON', 'PORTCH', 'DESCRIPTION']
    ['mgmt0', '--', 'up', '10.1.100.20', '100', '1500', '', '', '', '', '', '']
    ['mgmt1', '10', 'down', '10.1.100.2', '1000', '1500', '', '', '', '', '', '']

But, again, if I change only the Management line, I start to capture more:

    Management
      ^${INTERFACE}\s+${VRF}\s+${STATUS}\s+${IP}\s+${SPEED}\s+${MTU} -> Record
      ^.*---- -> Start

    Ethernet
      ^${INTERFACE}\s+${VLAN}\s+${TYPE}\s+${MODE}\s+${STATUS}\s+${REASON}\s+${SPEED}\s+${PORTCH} -> Record
      ^\n -> Start

    Loopback
      ^${INTERFACE}\s+${STATUS}\s+${DESCRIPTION} -> Record
      ^\n -> Start

    VLAN
      ^${INTERFACE}\s+${TYPE}\s+${STATUS}\s+${REASON} -> Record

    FSM Table:
    ['INTERFACE', 'VRF', 'STATUS', 'IP', 'SPEED', 'MTU', 'VLAN', 'TYPE', 'MODE', 'REASON', 'PORTCH', 'DESCRIPTION']
    ['mgmt0', '--', 'up', '10.1.100.20', '100', '1500', '', '', '', '', '', '']
    ['mgmt1', '10', 'down', '10.1.100.2', '1000', '1500', '', '', '', '', '', '']
    ['Eth1/1', '', 'down', '', 'auto(D)', '', '--', 'eth', 'routed', 'Administratively down', '--', '']
    ['Eth1/2', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'Administratively down', '--', '']
    ['Eth1/3', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/4', '', 'down', '', 'auto(D)', '', '2', 'eth', 'trunk', 'XCVR not inserted', '10', '']
    ['Eth1/5', '', 'down', '', 'auto(D)', '', '2', 'eth', 'trunk', 'XCVR not inserted', '10', '']
    ['Eth1/6', '', 'down', '', 'auto(D)', '', '2', 'eth', 'trunk', 'XCVR not inserted', '11', '']
    ['Eth1/7', '', 'down', '', 'auto(D)', '', '2', 'eth', 'trunk', 'XCVR not inserted', '11', '']
    ['Eth1/8', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/9', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/10', '', 'down', '', 'auto(D)', '', '--', 'eth', 'routed', 'XCVR not inserted', '--', '']
    ['Eth2/1', '', 'down', '', 'auto(D)', '', '--', 'eth', 'routed', 'Link not connected', '--', '']
    ['Eth2/2', '', 'down', '', 'auto(D)', '', '--', 'eth', 'routed', 'Link not connected', '--', '']
    ['Eth2/3', '', 'down', '', 'auto(D)', '', '--', 'eth', 'routed', 'Link not connected', '--', '']
    ['Eth2/4', '', 'down', '', 'auto(D)', '', '--', 'eth', 'routed', 'Link not connected', '--', '']
    ['Eth2/5', '', 'down', '', 'auto(D)', '', '2', 'eth', 'trunk', 'XCVR not inserted', '12', '']
    ['Eth2/6', '', 'down', '', 'auto(D)', '', '2', 'eth', 'trunk', 'XCVR not inserted', '12', '']
    ['Eth2/7', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth2/8', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Po10', '', 'down', '', 'auto(D)', '', '1', 'eth', 'trunk', 'No operational members', 'lacp', '']
    ['Po11', '', 'down', '', 'auto(D)', '', '1', 'eth', 'trunk', 'No operational members', 'lacp', '']
    ['Po12', '', 'down', '', 'auto(D)', '', '1', 'eth', 'trunk', 'No operational members', 'lacp', '']
    ['Vlan1', '', 'down', '', '', '', '', '--', '', 'Administratively down', '', '']
    ['Vlan5', '', 'down', '', '', '', '', '--', '', 'VLAN/BD is down', '', '']
    ['Vlan10', '', 'down', '', '', '', '', '--', '', 'VLAN/BD is down', '', '']
    ['Vlan20', '', 'down', '', '', '', '', '--', '', 'VLAN/BD is down', '', '']
    ['Vlan66', '', 'down', '', '', '', '', '--', '', 'Administratively down', '', '']
    ['Vlan77', '', 'down', '', '', '', '', '--', '', 'Administratively down', '', '']
    ['Vlan146', '', 'down', '', '', '', '', '--', '', 'Administratively down', '', '']

Honestly, this is gonna blow my mind D:

**Comment by jedelman8** [comment]
Hey, so you state this "Then, I want to go back to the Start state as soon as the "-----" pattern is catched and so I update my states" but including this "^.*---- -> Start" as a regex...

`.` is any character and `*` is 0 or more, so you'll pretty much match anything.  Why not get rid of the `.*`?

**Comment by GGabriele** [comment]
Here it is what I obtain:

    FSM Template:
    Value INTERFACE (\S+)
    Value VRF (\S+)
    Value STATUS (up|down)
    Value IP (\d+\.\d+\.\d+\.\d+)
    Value SPEED (\S+)
    Value MTU (\d+)
    Value VLAN ([\d+--]+)
    Value TYPE (\S+)
    Value MODE (routed|access|trunk)
    Value REASON (\S+(\s\S+)*)
    Value PORTCH (\S+)
    Value DESCRIPTION (\S+(\s\S+)*)

    Start
      ^Port\s+VRF\s+Status\s+IP\s+Address\s+Speed\s+MTU -> Management
      ^Ethernet\s+VLAN\s+Type\s+Mode\s+Status\s+Reason\s+Speed\s+Port -> Ethernet
      ^Interface\s+Status\s+Description -> Loopback
      ^Interface\s+Secondary\s+VLAN\(Type\)\s+Status\s+Reason -> VLAN

    Management
      ^${INTERFACE}\s+${VRF}\s+${STATUS}\s+${IP}\s+${SPEED}\s+${MTU} -> Record
      ^------ -> Start

    Ethernet
      ^${INTERFACE}\s+${VLAN}\s+${TYPE}\s+${MODE}\s+${STATUS}\s+${REASON}\s+${SPEED}\s+${PORTCH} -> Record
      ^------ -> Start

    Loopback
      ^${INTERFACE}\s+${STATUS}\s+${DESCRIPTION} -> Record
      ^------ -> Start

    VLAN
      ^${INTERFACE}\s+${TYPE}\s+${STATUS}\s+${REASON} -> Record


    FSM Table:
    ['INTERFACE', 'VRF', 'STATUS', 'IP', 'SPEED', 'MTU', 'VLAN', 'TYPE', 'MODE', 'REASON', 'PORTCH', 'DESCRIPTION']
    ['Vlan1', '', 'down', '', '', '', '', '--', '', 'Administratively down', '', '']
    ['Vlan5', '', 'down', '', '', '', '', '--', '', 'VLAN/BD is down', '', '']
    ['Vlan10', '', 'down', '', '', '', '', '--', '', 'VLAN/BD is down', '', '']
    ['Vlan20', '', 'down', '', '', '', '', '--', '', 'VLAN/BD is down', '', '']
    ['Vlan66', '', 'down', '', '', '', '', '--', '', 'Administratively down', '', '']
    ['Vlan77', '', 'down', '', '', '', '', '--', '', 'Administratively down', '', '']
    ['Vlan146', '', 'down', '', '', '', '', '--', '', 'Administratively down', '', '']

**Comment by jedelman8** [comment]
What do you get if you have this `^\s*----- -> Start` instead. Sometimes there are spaces not shown, etc.

**Comment by GGabriele** [comment]
I get the same as above.
Anyway, if I use this instead '^\s----- -> Start' (without the *) I catch Ethernet and Po interfaces. Still no Management and Vlan interfaces.

**Comment by GGabriele** [comment]
Okay I've found a solution for this but I don't know if it's the best one. 

I modified the Ethernet line on Start state from this:

    ^Ethernet\s+VLAN\s+Type\s+Mode\s+Status\s+Reason\s+Speed\s+Port -> Ethernet

to this:

    ^Interface\s+Ch.* -> Ethernet 

Due to some obscure reason, the first line does not work well.

Then I added a rule inside each state, for example:
    
    # the following line catches the first dashed line before the actual values
    ^.*----
    ^${INTERFACE}\s+${VRF}\s+${STATUS}\s+${IP}\s+${SPEED}\s+${MTU} -> Record
    # this catches everything and goes back to start.
    ^.* -> Start

    FSM Template:
    Value INTERFACE (\S+)
    Value VRF (\S+)
    Value STATUS (up|down)
    Value IP (\d+\.\d+\.\d+\.\d+)
    Value SPEED (\S+)
    Value MTU (\d+)
    Value VLAN ([\d+--]+)
    Value TYPE (\S+)
    Value MODE (routed|access|trunk)
    Value REASON (\S+(\s\S+)*)
    Value PORTCH (\S+)
    Value DESCRIPTION (\S+(\s\S+)*)

    Start
      ^Port\s+VRF\s+Status\s+IP\s+Address\s+Speed\s+MTU -> Management
      ^Interface\s+Ch.* -> Ethernet 
      ^Interface\s+Status\s+Description -> Loopback
      ^Interface\s+Secondary\s+VLAN\(Type\)\s+Status\s+Reason -> VLAN

    Management
      # the following line catches the first dashed line before the actual values
      ^.*----
      ^${INTERFACE}\s+${VRF}\s+${STATUS}\s+${IP}\s+${SPEED}\s+${MTU} -> Record
      # this catches everything and go back to start.
      ^.* -> Start

    Ethernet
      ^.*-----
     ^${INTERFACE}\s+${VLAN}\s+${TYPE}\s+${MODE}\s+${STATUS}\s+${REASON}\s+${SPEED}\s+${PORTCH} -> Record
      ^.* -> Start

    Loopback
      ^.*-----
      ^${INTERFACE}\s+${STATUS}\s+${DESCRIPTION} -> Record
      ^.* -> Start

    VLAN
      ^${INTERFACE}\s+${TYPE}\s+${STATUS}\s+${REASON} -> Record

    FSM Table:
    ['INTERFACE', 'VRF', 'STATUS', 'IP', 'SPEED', 'MTU', 'VLAN', 'TYPE', 'MODE', 'REASON', 'PORTCH', 'DESCRIPTION']
    ['mgmt0', '--', 'up', '10.1.100.20', '100', '1500', '', '', '', '', '', '']
    ['mgmt1', '10', 'down', '10.1.100.2', '1000', '1500', '', '', '', '', '', '']
    ['Eth1/1', '', 'down', '', 'auto(D)', '', '--', 'eth', 'routed', 'Administratively down', '--', '']
    ['Eth1/2', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'Administratively down', '--', '']
    ['Eth1/3', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/4', '', 'down', '', 'auto(D)', '', '2', 'eth', 'trunk', 'XCVR not inserted', '10', '']
    ['Eth1/5', '', 'down', '', 'auto(D)', '', '2', 'eth', 'trunk', 'XCVR not inserted', '10', '']
    ['Eth1/6', '', 'down', '', 'auto(D)', '', '2', 'eth', 'trunk', 'XCVR not inserted', '11', '']
    ['Eth1/7', '', 'down', '', 'auto(D)', '', '2', 'eth', 'trunk', 'XCVR not inserted', '11', '']
    ['Eth1/8', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/9', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/10', '', 'down', '', 'auto(D)', '', '--', 'eth', 'routed', 'XCVR not inserted', '--', '']
    ['Eth1/11', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/12', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/13', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/14', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/15', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/16', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/17', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/18', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/19', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/20', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/21', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/22', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/23', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/24', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/25', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/26', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/27', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/28', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/29', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/30', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/31', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/32', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/33', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/34', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/35', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/36', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/37', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/38', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/39', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/40', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/41', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/42', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/43', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/44', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/45', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/46', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/47', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth1/48', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth2/1', '', 'down', '', 'auto(D)', '', '--', 'eth', 'routed', 'Link not connected', '--', '']
    ['Eth2/2', '', 'down', '', 'auto(D)', '', '--', 'eth', 'routed', 'Link not connected', '--', '']
    ['Eth2/3', '', 'down', '', 'auto(D)', '', '--', 'eth', 'routed', 'Link not connected', '--', '']
    ['Eth2/4', '', 'down', '', 'auto(D)', '', '--', 'eth', 'routed', 'Link not connected', '--', '']
    ['Eth2/5', '', 'down', '', 'auto(D)', '', '2', 'eth', 'trunk', 'XCVR not inserted', '12', '']
    ['Eth2/6', '', 'down', '', 'auto(D)', '', '2', 'eth', 'trunk', 'XCVR not inserted', '12', '']
    ['Eth2/7', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth2/8', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth2/9', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth2/10', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'XCVR not inserted', '--', '']
    ['Eth2/11', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'Administratively down', '--', '']
    ['Eth2/12', '', 'down', '', 'auto(D)', '', '1', 'eth', 'access', 'Administratively down', '--', '']
    ['Lo10', '', 'up', '', '', '', '', '', '', '', '', '--']
    ['Vlan1', '', 'down', '', '', '', '', '--', '', 'Administratively down', '', '']
    ['Vlan5', '', 'down', '', '', '', '', '--', '', 'VLAN/BD is down', '', '']
    ['Vlan10', '', 'down', '', '', '', '', '--', '', 'VLAN/BD is down', '', '']
    ['Vlan20', '', 'down', '', '', '', '', '--', '', 'VLAN/BD is down', '', '']
    ['Vlan66', '', 'down', '', '', '', '', '--', '', 'Administratively down', '', '']
    ['Vlan77', '', 'down', '', '', '', '', '--', '', 'Administratively down', '', '']
    ['Vlan146', '', 'down', '', '', '', '', '--', '', 'Administratively down', '', '']
