### ISSUE TITLE
test-template.yml fails in ansible 2.0.0.2

### ISSUE THREAD

**Issue by pixelrebel** [networktocode/ntc-ansible#97]
With ansible 2.0.0.2, `ansible-playbook test-template.yml` fails for the task "extract command string from command_variable" with the following error:

```
TASK [extract command string from command_variable] ****************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! template error while templating string: unexpected 'end of template'"}
```

**Comment by jedelman8** [comment]
This shouldn't be used yet with Ansible 2.0.  Has not been tested or validated against 2.0.

Be patient.  For now, you'll want to stick with 1.9.x if you want to use these modules.

**Comment by pixelrebel** [comment]
Good to know, thanks.  In any case, here's a PR (https://github.com/networktocode/ntc-ansible/pull/98) that resolves this particular issue.
