### ISSUE TITLE
Add support for the use_keys option from netmiko

### ISSUE THREAD

**Issue by kadecole** [networktocode/ntc-ansible#99]
Add support to ntc-ansible so you can use an ssh key to login to the remote system. use_keys and key_file need to be added as methods so they can be passed to the netmiko module. 
```
  - ntc_show_command:
     connection=ssh
     platform=avaya_ers
     command='show vlan'
     host="{{ inventory_hostname }}"
     username="{{ username }}"
     password=""
     use_keys=true
     key_file="/home/manager/ansible/id_dsa"

**Comment by pixelrebel** [comment]
Check out this PR https://github.com/networktocode/ntc-ansible/pull/101 which adds support into the two netmiko modules.

**Comment by jedelman8** [comment]
Thanks @pixelrebel
